namespace UsdaFoodGenerator;

public static class FoodQueries
{
    // Curated list of common whole foods to search for.
    // The generator will find the best Foundation/SR Legacy match for each.
    public static readonly string[] All =
    [
        // ── Fruits ──
        "Strawberries, raw",
        "Blueberries, raw",
        "Raspberries, raw",
        "Blackberries, raw",
        "Banana, raw",
        "Apple, raw, with skin",
        "Orange, raw",
        "Grapes, raw",
        "Mango, raw",
        "Pineapple, raw",
        "Watermelon, raw",
        "Avocado, raw",
        "Peach, raw",
        "Pear, raw",
        "Cherries, sweet, raw",
        "Kiwifruit, raw",
        "Lemon, raw",
        "Lime, raw",
        "Grapefruit, raw",
        "Cantaloupe, raw",
        "Honeydew melon, raw",
        "Plum, raw",
        "Apricot, raw",
        "Papaya, raw",
        "Pomegranate, raw",
        "Cranberries, raw",
        "Passion fruit, raw",
        "Fig, raw",
        "Dates, deglet noor",
        "Raisins",
        "Coconut meat, raw",

        // ── Vegetables ──
        "Broccoli, raw",
        "Spinach, raw",
        "Carrot, raw",
        "Tomato, raw",
        "Sweet potato, raw",
        "Potato, raw",
        "Onion, raw",
        "Garlic, raw",
        "Cucumber, with peel, raw",
        "Bell pepper, red, raw",
        "Bell pepper, green, raw",
        "Lettuce, romaine, raw",
        "Lettuce, iceberg, raw",
        "Kale, raw",
        "Cauliflower, raw",
        "Zucchini, raw",
        "Mushrooms, white, raw",
        "Celery, raw",
        "Asparagus, raw",
        "Beetroot, raw",
        "Corn, sweet, yellow, raw",
        "Peas, green, raw",
        "Cabbage, raw",
        "Brussels sprouts, raw",
        "Eggplant, raw",
        "Artichoke, raw",
        "Radishes, raw",
        "Turnip, raw",
        "Green beans, raw",
        "Leek, raw",
        "Fennel, bulb, raw",
        "Okra, raw",
        "Bok choy, raw",
        "Swiss chard, raw",
        "Collard greens, raw",
        "Arugula, raw",
        "Watercress, raw",
        "Endive, raw",
        "Parsnip, raw",
        "Rutabaga, raw",
        "Jicama, raw",
        "Butternut squash, raw",
        "Acorn squash, raw",
        "Spaghetti squash, raw",
        "Pumpkin, raw",

        // ── Proteins — Poultry ──
        "Chicken breast, raw",
        "Chicken thigh, raw",
        "Chicken drumstick, raw",
        "Chicken wing, raw",
        "Turkey breast, raw",
        "Turkey, ground, raw",
        "Duck, meat only, raw",

        // ── Proteins — Beef ──
        "Beef, ground, 90% lean, raw",
        "Beef, ground, 80% lean, raw",
        "Beef, tenderloin, raw",
        "Beef, sirloin, raw",
        "Beef, ribeye, raw",
        "Beef, chuck roast, raw",
        "Beef, flank steak, raw",
        "Beef, brisket, raw",
        "Beef liver, raw",

        // ── Proteins — Pork ──
        "Pork loin, raw",
        "Pork chop, raw",
        "Pork tenderloin, raw",
        "Pork shoulder, raw",
        "Pork, ground, raw",
        "Bacon, raw",
        "Ham, sliced",

        // ── Proteins — Lamb & Game ──
        "Lamb, leg, raw",
        "Lamb, chop, raw",
        "Lamb, ground, raw",
        "Venison, raw",
        "Bison, ground, raw",

        // ── Proteins — Seafood ──
        "Salmon, Atlantic, raw",
        "Tuna, yellowfin, raw",
        "Tuna, canned in water",
        "Shrimp, raw",
        "Cod, Atlantic, raw",
        "Tilapia, raw",
        "Halibut, raw",
        "Sardines, canned in oil",
        "Mackerel, raw",
        "Trout, rainbow, raw",
        "Crab, blue, raw",
        "Lobster, raw",
        "Scallops, raw",
        "Mussels, raw",
        "Oysters, raw",
        "Clams, raw",
        "Catfish, raw",
        "Swordfish, raw",
        "Anchovies, canned in oil",
        "Squid, raw",
        "Octopus, raw",

        // ── Proteins — Eggs & Plant ──
        "Egg, whole, raw",
        "Egg white, raw",
        "Egg yolk, raw",
        "Tofu, firm",
        "Tofu, silken",
        "Tempeh",
        "Edamame, frozen",
        "Seitan",

        // ── Grains & Cereals ──
        "Rice, white, long-grain, raw",
        "Rice, brown, long-grain, raw",
        "Rice, basmati, raw",
        "Rice, jasmine, raw",
        "Rice, wild, raw",
        "Oats, raw",
        "Quinoa, raw",
        "Pasta, dry",
        "Pasta, whole wheat, dry",
        "Couscous, dry",
        "Bulgur, dry",
        "Barley, pearled, raw",
        "Farro, raw",
        "Millet, raw",
        "Buckwheat groats, raw",
        "Cornmeal, yellow",
        "Flour, all-purpose",
        "Flour, whole wheat",
        "Flour, almond",
        "Flour, coconut",
        "Bread, whole wheat",
        "Bread, white",
        "Bread, rye",
        "Bread, sourdough",
        "Tortilla, flour",
        "Tortilla, corn",
        "Bagel, plain",
        "English muffin",
        "Pita, whole wheat",
        "Croissant",
        "Pancake, plain",
        "Waffle, plain",
        "Granola",
        "Cornflakes",
        "Oatmeal, instant",

        // ── Legumes ──
        "Lentils, raw",
        "Chickpeas, raw",
        "Black beans, raw",
        "Kidney beans, raw",
        "Pinto beans, raw",
        "Navy beans, raw",
        "Lima beans, raw",
        "Split peas, raw",
        "Soybeans, raw",
        "Mung beans, raw",
        "Black-eyed peas, raw",
        "Cannellini beans, raw",

        // ── Dairy ──
        "Milk, whole",
        "Milk, 2%",
        "Milk, 1%",
        "Milk, skim",
        "Greek yogurt, plain, nonfat",
        "Greek yogurt, plain, whole milk",
        "Yogurt, plain, whole milk",
        "Yogurt, plain, low fat",
        "Cheese, cheddar",
        "Cheese, mozzarella",
        "Cheese, parmesan",
        "Cheese, swiss",
        "Cheese, gouda",
        "Cheese, brie",
        "Cheese, feta",
        "Cheese, cream cheese",
        "Cheese, ricotta",
        "Cheese, cottage",
        "Butter, salted",
        "Butter, unsalted",
        "Cream, heavy",
        "Cream, sour",
        "Half and half",
        "Whipped cream",
        "Kefir, plain",

        // ── Nuts & Seeds ──
        "Almonds, raw",
        "Walnuts, raw",
        "Peanuts, raw",
        "Cashews, raw",
        "Pecans, raw",
        "Pistachios, raw",
        "Macadamia nuts, raw",
        "Brazil nuts, raw",
        "Hazelnuts, raw",
        "Pine nuts, raw",
        "Chestnuts, raw",
        "Chia seeds",
        "Flaxseed",
        "Sunflower seeds, raw",
        "Pumpkin seeds, raw",
        "Sesame seeds",
        "Hemp seeds",
        "Poppy seeds",

        // ── Oils & Fats ──
        "Olive oil",
        "Coconut oil",
        "Canola oil",
        "Avocado oil",
        "Sesame oil",
        "Vegetable oil",
        "Flaxseed oil",
        "Walnut oil",
        "Ghee",
        "Lard",

        // ── Condiments & Sauces ──
        "Soy sauce",
        "Vinegar, balsamic",
        "Vinegar, apple cider",
        "Mustard, prepared",
        "Ketchup",
        "Mayonnaise",
        "Hot sauce",
        "Worcestershire sauce",
        "Fish sauce",
        "Tahini",
        "Hummus",
        "Salsa",
        "Pesto",
        "Sriracha",
        "BBQ sauce",
        "Teriyaki sauce",
        "Ranch dressing",

        // ── Sweeteners & Baking ──
        "Honey",
        "Maple syrup",
        "Sugar, granulated",
        "Sugar, brown",
        "Molasses",
        "Agave nectar",
        "Cocoa powder, unsweetened",
        "Dark chocolate, 70-85%",
        "Milk chocolate",
        "Baking powder",
        "Baking soda",
        "Vanilla extract",
        "Yeast, active dry",
        "Gelatin, dry powder",
        "Cornstarch",

        // ── Nut Butters & Spreads ──
        "Peanut butter, smooth",
        "Almond butter",
        "Cashew butter",
        "Sunflower seed butter",
        "Nutella",
        "Jam, strawberry",

        // ── Beverages ──
        "Coffee, brewed",
        "Tea, brewed, green",
        "Tea, brewed, black",
        "Orange juice",
        "Apple juice",
        "Coconut water",
        "Coconut milk, canned",
        "Almond milk, unsweetened",
        "Soy milk, unsweetened",
        "Oat milk",
        "Cranberry juice",
        "Tomato juice",
        "Lemonade",

        // ── Herbs & Spices ──
        "Basil, fresh",
        "Cilantro, raw",
        "Parsley, fresh",
        "Mint, fresh",
        "Rosemary, fresh",
        "Thyme, fresh",
        "Dill, fresh",
        "Ginger, raw",
        "Turmeric, ground",
        "Cinnamon, ground",
        "Cumin, ground",
        "Paprika",
        "Black pepper, ground",
        "Chili powder",
        "Oregano, dried",
        "Cayenne pepper",
        "Nutmeg, ground",
        "Cloves, ground",
        "Coriander, ground",
        "Garlic powder",
        "Onion powder",
        "Salt, table",

        // ── Dried Fruits & Snacks ──
        "Dried apricots",
        "Dried cranberries",
        "Dried mango",
        "Prunes",
        "Trail mix",
        "Popcorn, air-popped",
        "Rice cakes",
        "Tortilla chips",
        "Potato chips",
        "Pretzels",

        // ── Prepared / Common ──
        "Tofu, extra firm",
        "Sauerkraut",
        "Kimchi",
        "Pickles, dill",
        "Olives, black, canned",
        "Olives, green",
        "Capers",
        "Sun-dried tomatoes",
        "Artichoke hearts, canned",
        "Roasted red peppers, jarred",
        "Coconut, shredded, sweetened",
        "Coconut, shredded, unsweetened",
    ];
}
