#!/usr/bin/env python3
"""
AUSNUT 2023 → AustralianFoodsDatabase.cs generator.

Note: Records generated before this change may encode missing optional nutrients as 0; regenerate to correct.

Usage:
    pip install openpyxl
    python generate.py --input data/AUSNUT2023.xlsx --output ../../backend/src/GutAI.Infrastructure/Data/AustralianFoodsDatabase.cs

The script reads the AUSNUT 2011-13 / 2023 nutrient file (Excel),
converts kJ → kcal and sodium mg → g, then emits a static C# file
in the same format as WholeFoodsDatabase.cs.

Expected columns (by name or position):
  - Food Name (col B or "Food Name")
  - Energy kJ (col with "Energy" and "kJ")
  - Protein g
  - Carbohydrate g (or "Available carbohydrate")
  - Fat g (or "Total fat")
  - Dietary fibre g
  - Total sugars g
  - Sodium mg
"""
import argparse
import re
import sys
from pathlib import Path

try:
    from openpyxl import load_workbook
except ImportError:
    print("pip install openpyxl", file=sys.stderr)
    sys.exit(1)


KJ_TO_KCAL = 4.184


def find_column(headers: list[str], *patterns: str) -> int | None:
    for i, h in enumerate(headers):
        hl = (h or "").lower()
        if all(p.lower() in hl for p in patterns):
            return i
    return None


def clean_name(name: str) -> str:
    # Remove AUSNUT food codes in parentheses at start, e.g., "(12345678) Bread, white"
    name = re.sub(r"^\(\d+\)\s*", "", name)
    return name.strip()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Path to AUSNUT Excel file")
    parser.add_argument("--output", required=True, help="Output .cs file path")
    args = parser.parse_args()

    wb = load_workbook(args.input, read_only=True, data_only=True)
    ws = wb.active

    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        print("Empty workbook", file=sys.stderr)
        sys.exit(1)

    headers = [str(c) if c else "" for c in rows[0]]
    col_name = find_column(headers, "food", "name") or find_column(headers, "name") or 1
    col_energy = find_column(headers, "energy", "kj")
    col_protein = find_column(headers, "protein")
    col_carbs = find_column(headers, "carbohydrate") or find_column(headers, "carb")
    col_fat = find_column(headers, "fat")
    col_fibre = find_column(headers, "fibre") or find_column(headers, "fiber")
    col_sugar = find_column(headers, "sugar")
    col_sodium = find_column(headers, "sodium")

    if col_energy is None:
        print("Could not find Energy (kJ) column", file=sys.stderr)
        sys.exit(1)

    foods: list[tuple] = []
    seen: set[str] = set()

    for row in rows[1:]:
        name_raw = row[col_name]
        if not name_raw or not str(name_raw).strip():
            continue

        name = clean_name(str(name_raw))
        if name in seen:
            continue
        seen.add(name)

        def val(col_idx, default=0.0):
            if col_idx is None:
                return default
            v = row[col_idx]
            if v is None:
                return default
            try:
                return float(v)
            except (ValueError, TypeError):
                return default

        def opt_val(col_idx):
            if col_idx is None:
                return None
            v = row[col_idx]
            if v is None:
                return None
            try:
                return float(v)
            except (ValueError, TypeError):
                return None

        energy_kj = val(col_energy, default=0.0)
        cal = round(energy_kj / KJ_TO_KCAL)
        protein = round(val(col_protein, default=0.0), 2)
        carbs = round(val(col_carbs, default=0.0), 2)
        fat = round(val(col_fat, default=0.0), 2)
        
        fibre_raw = opt_val(col_fibre)
        fibre = round(fibre_raw, 2) if fibre_raw is not None else None
        
        sugar_raw = opt_val(col_sugar)
        sugar = round(sugar_raw, 2) if sugar_raw is not None else None
        
        sodium_mg = opt_val(col_sodium)
        sodium_g = round(sodium_mg / 1000, 4) if sodium_mg is not None else None

        foods.append((name, cal, protein, carbs, fat, fibre, sugar, sodium_g))
    print(f"Parsed {len(foods)} foods from AUSNUT data")

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)

    def format_decimal(v):
        if v is None:
            return "null"
        return f"{v}m"

    with open(out, "w") as f:
        f.write('// <auto-generated>\n')
        f.write(f'// Generated from AUSNUT data. Total foods: {len(foods)}\n')
        f.write('// Note: Records generated before this change may encode missing optional nutrients as 0; regenerate to correct.\n')
        f.write('// Nutrient values per 100g. Sodium in GRAMS.\n')
        f.write('// Do not edit manually — re-run tools/AusnutFoodGenerator/generate.py\n')
        f.write('// </auto-generated>\n\n')
        f.write('using GutAI.Application.Common.DTOs;\n\n')
        f.write('namespace GutAI.Infrastructure.Data;\n\n')
        f.write('public static class AustralianFoodsDatabase\n{\n')
        f.write('    private static readonly List<FoodProductDto> Foods =\n    [\n')

        for name, cal, protein, carbs, fat_val, fibre, sugar, sodium in foods:
            escaped = name.replace('"', '\\"')
            fib_str = format_decimal(fibre)
            sug_str = format_decimal(sugar)
            sod_str = format_decimal(sodium)
            f.write(f'        F("{escaped}", {cal}, {protein}m, {carbs}m, {fat_val}m, {fib_str}, {sug_str}, {sod_str}),\n')

        f.write('    ];\n\n')
        f.write('    private static readonly Lazy<FoodSearchIndex> _index = new(\n')
        f.write('        () => new FoodSearchIndex(Foods), isThreadSafe: true);\n\n')
        f.write('    public static List<FoodProductDto> Search(string query, int maxResults = 10)\n')
        f.write('    {\n')
        f.write('        if (string.IsNullOrWhiteSpace(query)) return [];\n')
        f.write('        return _index.Value.Search(query, maxResults);\n')
        f.write('    }\n\n')
        f.write('    // Note: Records generated before this change may encode missing optional nutrients as 0; regenerate to correct.\n')
        f.write('    private static FoodProductDto F(string name, int cal, decimal protein, decimal carbs, decimal fat, decimal? fiber, decimal? sugar, decimal? sodium) =>\n')
        f.write('        new()\n')
        f.write('        {\n')
        f.write('            Name = name,\n')
        f.write('            Calories100g = cal,\n')
        f.write('            Protein100g = protein,\n')
        f.write('            Carbs100g = carbs,\n')
        f.write('            Fat100g = fat,\n')
        f.write('            Fiber100g = fiber,\n')
        f.write('            Sugar100g = sugar,\n')
        f.write('            SodiumMg100g = sodium.HasValue ? sodium.Value * 1000m : null,\n')
        f.write('            DataSource = "AUSNUT",\n')
        f.write('            SourceVersion = "AUSNUT 2011-13",\n')
        f.write('            LicenseType = "CC BY 2.5 AU",\n')
        f.write('            Attribution = "Food Standards Australia New Zealand",\n')
        f.write('            FoodKind = GutAI.Domain.Enums.FoodKind.WholeFood,\n')
        f.write('        };\n')
        f.write('}\n')

    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
