using System.Text.RegularExpressions;

namespace GutAI.Infrastructure.Services;

internal static class GlycemicData
{
    internal record GiEntry(string Pattern, Regex Regex, int GI, string Category, string Source, string Notes, string[]? Exclusions = null, bool IsEstimated = false);

    /// <summary>
    /// Pre-compiled, pre-sorted (by pattern length descending) GI database (353 entries).
    /// Sources: Sydney University GI Database, Harvard Health, Monash University.
    /// </summary>
    internal static readonly IReadOnlyList<GiEntry> GiDatabase;

    static GlycemicData()
    {
        var entries = new List<GiEntry>
        {
            // ── Breads & Bakery ─────────────────────────────────────────
            Entry("whole wheat bread", 74, "High", "Sydney Uni GI DB", "Whole wheat/wholemeal bread"),
            Entry("wholegrain bread", 51, "Low", "Sydney Uni GI DB", "Dense wholegrain bread"),
            Entry("sourdough rye", 48, "Low", "Sydney Uni GI DB", "Sourdough rye bread"),
            Entry("white bread", 75, "High", "Sydney Uni GI DB", "Standard white bread"),
            Entry("rye bread", 58, "Medium", "Sydney Uni GI DB", "Dense rye bread, varies by density"),
            Entry("sourdough bread", 54, "Low", "Sydney Uni GI DB", "Fermentation lowers GI"),
            Entry("pumpernickel", 50, "Low", "Sydney Uni GI DB", "Dense dark rye bread"),
            Entry("multigrain bread", 53, "Low", "Sydney Uni GI DB", "Depends on grain content"),
            Entry("pita bread", 57, "Medium", "Sydney Uni GI DB", "White pita bread"),
            Entry("bagel", 72, "High", "Sydney Uni GI DB", "White bagel"),
            Entry("croissant", 67, "Medium", "Sydney Uni GI DB", "Butter croissant"),
            Entry("baguette", 73, "High", "Sydney Uni GI DB", "French baguette"),
            Entry("naan", 71, "High", "Sydney Uni GI DB", "Indian flatbread"),
            Entry("chapati", 52, "Low", "Sydney Uni GI DB", "Indian whole wheat flatbread"),
            Entry("tortilla", 30, "Low", "Harvard Health", "Corn tortilla; wheat tortilla ~30"),
            Entry("brioche", 68, "Medium", "Estimated", "Enriched wheat bread", isEstimated: true),
            Entry("focaccia", 63, "Medium", "Estimated", "Italian flatbread", isEstimated: true),
            Entry("crumpet", 69, "Medium", "Sydney Uni GI DB", "English crumpet"),
            Entry("english muffin", 77, "High", "Sydney Uni GI DB", "Toasted English muffin"),
            Entry("waffle", 76, "High", "Sydney Uni GI DB", "Frozen waffle"),
            Entry("pancake", 67, "Medium", "Sydney Uni GI DB", "Pancake from mix"),
            Entry("scone", 92, "High", "Sydney Uni GI DB", "Plain scone"),
            Entry("ciabatta", 73, "High", "Estimated", "Italian white bread", isEstimated: true),
            Entry("lavash", 69, "Medium", "Estimated", "Thin flatbread", isEstimated: true),
            Entry("cornbread", 65, "Medium", "Estimated", "Cornmeal bread", isEstimated: true),
            Entry("breadstick", 72, "High", "Estimated", "Plain breadstick/grissini", isEstimated: true),
            Entry("hot cross bun", 65, "Medium", "Estimated", "Spiced sweet bun", isEstimated: true),
            Entry("crouton", 72, "High", "Estimated", "Oven-baked bread cubes", isEstimated: true),
            Entry("bread", 75, "High", "Sydney Uni GI DB", "Generic white bread", ["breadfruit", "breadcrumb", "gingerbread", "shortbread", "cornbread", "breadstick"]),

            // ── Rice & Grains ───────────────────────────────────────────
            Entry("jasmine rice", 89, "High", "Sydney Uni GI DB", "Thai jasmine rice, very high GI"),
            Entry("sushi rice", 73, "High", "Estimated", "Seasoned short-grain rice", isEstimated: true),
            Entry("sticky rice", 87, "High", "Sydney Uni GI DB", "Glutinous/sticky rice"),
            Entry("white rice", 73, "High", "Sydney Uni GI DB", "Medium grain white rice"),
            Entry("brown rice", 68, "Medium", "Sydney Uni GI DB", "Long grain brown rice"),
            Entry("basmati rice", 58, "Medium", "Sydney Uni GI DB", "Long grain basmati"),
            Entry("wild rice", 45, "Low", "Sydney Uni GI DB", "Wild rice blend"),
            Entry("arborio rice", 69, "Medium", "Estimated", "Risotto rice", isEstimated: true),
            Entry("rice noodles", 53, "Low", "Sydney Uni GI DB", "Rice vermicelli"),
            Entry("soba noodles", 46, "Low", "Sydney Uni GI DB", "Buckwheat soba"),
            Entry("udon", 55, "Medium", "Sydney Uni GI DB", "Japanese wheat noodles"),
            Entry("spaghetti", 49, "Low", "Sydney Uni GI DB", "Durum wheat spaghetti, al dente"),
            Entry("fettuccine", 40, "Low", "Sydney Uni GI DB", "Egg fettuccine"),
            Entry("macaroni", 47, "Low", "Sydney Uni GI DB", "Elbow macaroni"),
            Entry("rice", 73, "High", "Sydney Uni GI DB", "Generic white rice", ["licorice", "rice milk", "rice cake", "rice noodle", "rice paper", "rice pudding", "rice flour", "rice bran", "rice vinegar", "rice wine", "rice syrup", "brown rice syrup", "rice protein", "rice cracker", "rice vermicelli"]),
            Entry("pasta", 49, "Low", "Sydney Uni GI DB", "Durum wheat pasta", ["pasta sauce"]),
            Entry("noodle", 47, "Low", "Sydney Uni GI DB", "Wheat noodle, boiled"),
            Entry("couscous", 65, "Medium", "Sydney Uni GI DB", "Wheat couscous"),
            Entry("quinoa", 53, "Low", "Sydney Uni GI DB", "Cooked quinoa"),
            Entry("bulgur", 48, "Low", "Sydney Uni GI DB", "Cracked wheat bulgur"),
            Entry("barley", 28, "Low", "Sydney Uni GI DB", "Pearl barley"),
            Entry("oats", 55, "Medium", "Sydney Uni GI DB", "Rolled oats, cooked"),
            Entry("oat", 55, "Medium", "Sydney Uni GI DB", "Rolled oats, cooked"),
            Entry("millet", 71, "High", "Sydney Uni GI DB", "Cooked millet"),
            Entry("polenta", 68, "Medium", "Sydney Uni GI DB", "Cornmeal polenta"),
            Entry("amaranth", 97, "High", "Sydney Uni GI DB", "Popped amaranth"),
            Entry("buckwheat", 49, "Low", "Sydney Uni GI DB", "Buckwheat groats"),
            Entry("sorghum", 62, "Medium", "Harvard Health", "Whole grain sorghum"),
            Entry("congee", 78, "High", "Sydney Uni GI DB", "Rice porridge/congee"),
            Entry("mochi", 85, "High", "Estimated", "Japanese rice cake", isEstimated: true),
            Entry("taro", 54, "Low", "Sydney Uni GI DB", "Boiled taro"),
            Entry("farro", 40, "Low", "Estimated", "Ancient wheat grain", isEstimated: true),
            Entry("rice flour", 95, "High", "Sydney Uni GI DB", "White rice flour"),
            Entry("cornflour", 85, "High", "Estimated", "Cornstarch/cornflour", isEstimated: true),
            Entry("cream of wheat", 66, "Medium", "Sydney Uni GI DB", "Cream of wheat porridge"),
            Entry("grits", 69, "Medium", "Sydney Uni GI DB", "Corn grits"),
            Entry("teff", 57, "Medium", "Estimated", "Ethiopian teff grain", isEstimated: true),
            Entry("freekeh", 43, "Low", "Estimated", "Roasted green wheat", isEstimated: true),
            Entry("semolina", 60, "Medium", "Estimated", "Durum wheat semolina", isEstimated: true),
            Entry("egg noodles", 46, "Low", "Estimated", "Boiled egg noodles", isEstimated: true),
            Entry("instant noodles", 52, "Low", "Estimated", "Deep-fried instant noodles", isEstimated: true),
            Entry("rice vermicelli", 53, "Low", "Sydney Uni GI DB", "Thin rice noodles"),
            Entry("gnocchi", 68, "Medium", "Estimated", "Potato gnocchi", isEstimated: true),
            Entry("risotto", 69, "Medium", "Estimated", "Arborio rice risotto", isEstimated: true),
            Entry("tapioca", 67, "Medium", "Sydney Uni GI DB", "Tapioca/cassava starch"),

            // ── Potatoes & Starchy Vegetables ───────────────────────────
            Entry("baked potato", 85, "High", "Sydney Uni GI DB", "Russet baked potato"),
            Entry("mashed potato", 83, "High", "Sydney Uni GI DB", "Mashed with milk/butter"),
            Entry("instant mashed potato", 87, "High", "Sydney Uni GI DB", "Instant mashed potato flakes"),
            Entry("potato wedge", 75, "High", "Estimated", "Oven-baked potato wedges", isEstimated: true),
            Entry("hash brown", 72, "High", "Estimated", "Fried shredded potato", isEstimated: true),
            Entry("french fries", 63, "Medium", "Sydney Uni GI DB", "Deep-fried potato"),
            Entry("sweet potato", 63, "Medium", "Sydney Uni GI DB", "Boiled sweet potato"),
            Entry("potato", 78, "High", "Sydney Uni GI DB", "Boiled white potato"),
            Entry("yuca", 46, "Low", "Sydney Uni GI DB", "Boiled cassava/yuca"),
            Entry("cassava", 46, "Low", "Sydney Uni GI DB", "Boiled cassava"),
            Entry("plantain", 55, "Medium", "Sydney Uni GI DB", "Boiled ripe plantain"),
            Entry("yam", 37, "Low", "Sydney Uni GI DB", "Boiled yam"),
            Entry("parsnip", 52, "Low", "Sydney Uni GI DB", "Boiled parsnip"),
            Entry("pumpkin", 66, "Medium", "Sydney Uni GI DB", "Boiled pumpkin"),
            Entry("corn", 52, "Low", "Sydney Uni GI DB", "Sweet corn", ["unicorn", "corner", "cornucopia", "corned", "cornflour", "cornstarch", "corn syrup", "corn oil", "acorn", "popcorn"]),
            Entry("butternut squash", 51, "Low", "Sydney Uni GI DB", "Baked butternut squash"),
            Entry("turnip", 62, "Medium", "Sydney Uni GI DB", "Boiled turnip"),
            Entry("breadfruit", 60, "Medium", "Estimated", "Boiled breadfruit", isEstimated: true),
            Entry("celeriac", 35, "Low", "Estimated", "Boiled celeriac", isEstimated: true),

            // ── Fruits ──────────────────────────────────────────────────
            Entry("watermelon", 76, "High", "Sydney Uni GI DB", "High GI but low GL per serve"),
            Entry("pineapple", 59, "Medium", "Sydney Uni GI DB", "Fresh pineapple"),
            Entry("cantaloupe", 65, "Medium", "Sydney Uni GI DB", "Rockmelon/cantaloupe"),
            Entry("banana", 51, "Low", "Sydney Uni GI DB", "Ripe banana; less ripe=lower GI"),
            Entry("grape", 46, "Low", "Sydney Uni GI DB", "Fresh grapes", ["grapefruit"]),
            Entry("grapefruit", 25, "Low", "Sydney Uni GI DB", "Fresh grapefruit"),
            Entry("orange", 43, "Low", "Sydney Uni GI DB", "Fresh orange"),
            Entry("apple", 36, "Low", "Sydney Uni GI DB", "Fresh apple with skin", ["pineapple"]),
            Entry("pear", 38, "Low", "Sydney Uni GI DB", "Fresh pear"),
            Entry("peach", 42, "Low", "Sydney Uni GI DB", "Fresh peach"),
            Entry("plum", 39, "Low", "Sydney Uni GI DB", "Fresh plum"),
            Entry("strawberry", 40, "Low", "Sydney Uni GI DB", "Fresh strawberries"),
            Entry("blueberry", 53, "Low", "Sydney Uni GI DB", "Fresh blueberries"),
            Entry("raspberry", 32, "Low", "Sydney Uni GI DB", "Fresh raspberries"),
            Entry("cherry", 22, "Low", "Sydney Uni GI DB", "Fresh cherries"),
            Entry("mango", 51, "Low", "Sydney Uni GI DB", "Fresh mango"),
            Entry("papaya", 56, "Medium", "Sydney Uni GI DB", "Fresh papaya"),
            Entry("kiwi", 50, "Low", "Sydney Uni GI DB", "Fresh kiwifruit"),
            Entry("fig", 61, "Medium", "Sydney Uni GI DB", "Fresh fig", ["figure", "figment"]),
            Entry("date", 42, "Low", "Sydney Uni GI DB", "Fresh/dried dates", ["update", "mandate", "dated"]),
            Entry("persimmon", 50, "Low", "Estimated", "Fresh persimmon", isEstimated: true),
            Entry("lychee", 57, "Medium", "Sydney Uni GI DB", "Fresh lychee"),
            Entry("longan", 48, "Low", "Estimated", "Fresh longan", isEstimated: true),
            Entry("jackfruit", 50, "Low", "Estimated", "Fresh jackfruit", isEstimated: true),
            Entry("coconut", 45, "Low", "Estimated", "Fresh coconut meat", isEstimated: true),
            Entry("pomegranate", 53, "Low", "Estimated", "Fresh pomegranate", isEstimated: true),
            Entry("prune", 29, "Low", "Sydney Uni GI DB", "Dried prunes"),
            Entry("raisin", 64, "Medium", "Sydney Uni GI DB", "Dried raisins"),
            Entry("dried apricot", 30, "Low", "Sydney Uni GI DB", "Dried apricots"),
            Entry("dried cranberry", 62, "Medium", "Estimated", "Sweetened dried cranberries", isEstimated: true),
            Entry("guava", 12, "Low", "Sydney Uni GI DB", "Fresh guava"),
            Entry("passion fruit", 30, "Low", "Estimated", "Fresh passion fruit", isEstimated: true),
            Entry("dragon fruit", 48, "Low", "Estimated", "Fresh dragon fruit/pitaya", isEstimated: true),
            Entry("cranberry", 45, "Low", "Estimated", "Fresh cranberries", isEstimated: true),
            Entry("blackberry", 25, "Low", "Estimated", "Fresh blackberries", isEstimated: true),
            Entry("apricot", 34, "Low", "Sydney Uni GI DB", "Fresh apricot"),
            Entry("nectarine", 43, "Low", "Estimated", "Fresh nectarine", isEstimated: true),
            Entry("avocado", 15, "Low", "Estimated", "Fresh avocado — very low GI/GL", isEstimated: true),
            Entry("starfruit", 48, "Low", "Estimated", "Fresh starfruit/carambola", isEstimated: true),

            // ── Juices & Beverages ──────────────────────────────────────
            Entry("orange juice", 50, "Low", "Sydney Uni GI DB", "Fresh-squeezed OJ"),
            Entry("apple juice", 41, "Low", "Sydney Uni GI DB", "Unsweetened apple juice"),
            Entry("grape juice", 48, "Low", "Sydney Uni GI DB", "Grape juice"),
            Entry("cranberry juice", 52, "Low", "Sydney Uni GI DB", "Cranberry juice cocktail"),
            Entry("tomato juice", 38, "Low", "Sydney Uni GI DB", "Tomato juice"),
            Entry("carrot juice", 43, "Low", "Sydney Uni GI DB", "Fresh carrot juice"),
            Entry("pineapple juice", 46, "Low", "Sydney Uni GI DB", "Unsweetened pineapple juice"),
            Entry("sports drink", 78, "High", "Sydney Uni GI DB", "Glucose-based sports drink"),
            Entry("energy drink", 70, "High", "Estimated", "Sugar-based energy drink", isEstimated: true),
            Entry("soft drink", 63, "Medium", "Sydney Uni GI DB", "Sugar-sweetened soda"),
            Entry("cola", 63, "Medium", "Sydney Uni GI DB", "Regular cola"),
            Entry("oat milk", 69, "Medium", "Estimated", "Commercial oat milk", isEstimated: true),
            Entry("almond milk", 25, "Low", "Estimated", "Unsweetened almond milk", isEstimated: true),
            Entry("soy milk", 34, "Low", "Sydney Uni GI DB", "Unsweetened soy milk"),
            Entry("rice milk", 86, "High", "Sydney Uni GI DB", "Rice milk"),
            Entry("coconut water", 55, "Medium", "Estimated", "Pure coconut water", isEstimated: true),
            Entry("kombucha", 35, "Low", "Estimated", "Fermented tea drink", isEstimated: true),
            Entry("smoothie", 44, "Low", "Estimated", "Fruit smoothie — varies by ingredients", isEstimated: true),
            Entry("milkshake", 55, "Medium", "Estimated", "Milk-based milkshake", isEstimated: true),
            Entry("hot chocolate", 51, "Low", "Estimated", "Hot chocolate drink", isEstimated: true),
            Entry("chocolate milk", 42, "Low", "Sydney Uni GI DB", "Flavoured chocolate milk"),
            Entry("iced tea", 50, "Low", "Estimated", "Sweetened iced tea", isEstimated: true),
            Entry("ginger beer", 60, "Medium", "Estimated", "Sugar-sweetened ginger beer", isEstimated: true),
            Entry("fruit punch", 67, "Medium", "Estimated", "Sugar-sweetened fruit punch", isEstimated: true),

            // ── Legumes ─────────────────────────────────────────────────
            Entry("lentils", 26, "Low", "Sydney Uni GI DB", "Red/green lentils, boiled"),
            Entry("lentil", 26, "Low", "Sydney Uni GI DB", "Red/green lentils, boiled"),
            Entry("chickpea", 28, "Low", "Sydney Uni GI DB", "Canned/boiled chickpeas"),
            Entry("kidney bean", 24, "Low", "Sydney Uni GI DB", "Canned kidney beans"),
            Entry("black bean", 30, "Low", "Sydney Uni GI DB", "Canned black beans"),
            Entry("navy bean", 31, "Low", "Sydney Uni GI DB", "Canned navy beans"),
            Entry("baked bean", 48, "Low", "Sydney Uni GI DB", "Canned baked beans in sauce"),
            Entry("split pea", 25, "Low", "Sydney Uni GI DB", "Boiled split peas"),
            Entry("lima bean", 31, "Low", "Sydney Uni GI DB", "Boiled lima beans"),
            Entry("edamame", 18, "Low", "Estimated", "Steamed edamame", isEstimated: true),
            Entry("hummus", 6, "Low", "Sydney Uni GI DB", "Chickpea hummus"),
            Entry("soybean", 16, "Low", "Sydney Uni GI DB", "Boiled soybeans"),
            Entry("pinto bean", 39, "Low", "Sydney Uni GI DB", "Canned pinto beans"),
            Entry("fava bean", 40, "Low", "Sydney Uni GI DB", "Boiled fava beans"),
            Entry("mung bean", 31, "Low", "Sydney Uni GI DB", "Boiled mung beans"),
            Entry("cannellini bean", 31, "Low", "Sydney Uni GI DB", "Canned cannellini beans"),
            Entry("broad bean", 40, "Low", "Estimated", "Boiled broad beans", isEstimated: true),
            Entry("butter bean", 31, "Low", "Sydney Uni GI DB", "Canned butter/lima beans"),
            Entry("falafel", 32, "Low", "Estimated", "Deep-fried chickpea falafel", isEstimated: true),

            // ── Sugars & Sweeteners ─────────────────────────────────────
            Entry("glucose", 100, "High", "Sydney Uni GI DB", "Pure glucose (reference)"),
            Entry("sucrose", 65, "Medium", "Sydney Uni GI DB", "Table sugar"),
            Entry("fructose", 15, "Low", "Sydney Uni GI DB", "Pure fructose (low GI but high FODMAP)"),
            Entry("honey", 55, "Medium", "Sydney Uni GI DB", "Mixed floral honey"),
            Entry("maple syrup", 54, "Low", "Sydney Uni GI DB", "Pure maple syrup"),
            Entry("agave", 15, "Low", "Sydney Uni GI DB", "Agave nectar"),
            Entry("high fructose corn syrup", 62, "Medium", "Estimated", "HFCS-55", isEstimated: true),
            Entry("coconut sugar", 35, "Low", "Estimated", "Unrefined coconut sugar", isEstimated: true),
            Entry("brown sugar", 65, "Medium", "Sydney Uni GI DB", "Brown sugar"),
            Entry("molasses", 55, "Medium", "Estimated", "Blackstrap molasses", isEstimated: true),
            Entry("sugar", 65, "Medium", "Sydney Uni GI DB", "White table sugar", ["sugar free", "sugar-free", "sugar snap", "sugar alcohol", "coconut sugar", "brown sugar", "sugar cane"]),

            // ── Dairy & Alternatives ────────────────────────────────────
            Entry("yogurt", 36, "Low", "Sydney Uni GI DB", "Plain yogurt"),
            Entry("ice cream", 51, "Low", "Sydney Uni GI DB", "Regular vanilla ice cream"),
            Entry("milk", 37, "Low", "Sydney Uni GI DB", "Full cream milk", ["milk chocolate", "almond milk", "oat milk", "soy milk", "coconut milk", "rice milk", "milk powder", "milk solid", "milkshake", "buttermilk", "chocolate milk"]),
            Entry("custard", 43, "Low", "Sydney Uni GI DB", "Egg custard"),
            Entry("cottage cheese", 27, "Low", "Estimated", "Low GI cottage cheese", isEstimated: true),
            Entry("cream cheese", 27, "Low", "Estimated", "Cream cheese — minimal carbs", isEstimated: true),

            // ── Snacks & Processed ──────────────────────────────────────
            Entry("popcorn", 55, "Medium", "Sydney Uni GI DB", "Plain air-popped popcorn"),
            Entry("pretzel", 83, "High", "Sydney Uni GI DB", "Hard pretzel"),
            Entry("rice cake", 87, "High", "Sydney Uni GI DB", "Puffed rice cakes"),
            Entry("rice cracker", 87, "High", "Estimated", "Puffed rice crackers", isEstimated: true),
            Entry("corn chip", 63, "Medium", "Sydney Uni GI DB", "Corn/tortilla chips"),
            Entry("potato chip", 54, "Low", "Sydney Uni GI DB", "Potato crisps/chips"),
            Entry("granola bar", 61, "Medium", "Estimated", "Oat-based granola bar", isEstimated: true),
            Entry("nut bar", 22, "Low", "Estimated", "Nut-based snack bar", isEstimated: true),
            Entry("protein bar", 38, "Low", "Estimated", "Whey protein bar, varies widely", isEstimated: true),
            Entry("dark chocolate", 23, "Low", "Sydney Uni GI DB", "70%+ dark chocolate"),
            Entry("milk chocolate", 43, "Low", "Sydney Uni GI DB", "Milk chocolate"),
            Entry("white chocolate", 44, "Low", "Estimated", "White chocolate", isEstimated: true),
            Entry("cookie", 62, "Medium", "Sydney Uni GI DB", "Plain cookie/biscuit"),
            Entry("cake", 67, "Medium", "Sydney Uni GI DB", "Sponge cake", ["rice cake", "pancake", "cheesecake", "cupcake", "oatcake", "fish cake"]),
            Entry("brownie", 42, "Low", "Estimated", "Chocolate brownie", isEstimated: true),
            Entry("donut", 76, "High", "Sydney Uni GI DB", "Glazed donut"),
            Entry("doughnut", 76, "High", "Sydney Uni GI DB", "Glazed doughnut"),
            Entry("muffin", 62, "Medium", "Sydney Uni GI DB", "Blueberry muffin"),
            Entry("cracker", 74, "High", "Sydney Uni GI DB", "Water crackers"),
            Entry("pizza", 60, "Medium", "Sydney Uni GI DB", "Cheese pizza"),
            Entry("hamburger bun", 61, "Medium", "Sydney Uni GI DB", "White hamburger bun"),
            Entry("taco shell", 68, "Medium", "Estimated", "Corn taco shell", isEstimated: true),
            Entry("nachos", 63, "Medium", "Estimated", "Corn nachos with toppings", isEstimated: true),
            Entry("ice cream cone", 63, "Medium", "Estimated", "Wafer ice cream cone", isEstimated: true),
            Entry("jelly bean", 78, "High", "Sydney Uni GI DB", "Jelly beans"),
            Entry("gummy bear", 78, "High", "Estimated", "Gummy bear sweets", isEstimated: true),
            Entry("marshmallow", 62, "Medium", "Estimated", "Plain marshmallows", isEstimated: true),
            Entry("licorice", 78, "High", "Sydney Uni GI DB", "Licorice/liquorice candy"),
            Entry("toffee", 65, "Medium", "Estimated", "Toffee candy", isEstimated: true),
            Entry("fudge", 65, "Medium", "Estimated", "Chocolate fudge", isEstimated: true),
            Entry("candy", 70, "High", "Estimated", "Sugar-based hard candy", isEstimated: true),

            // ── Cereals & Breakfast ─────────────────────────────────────
            Entry("cornflakes", 81, "High", "Sydney Uni GI DB", "Kellogg's Corn Flakes"),
            Entry("rice krispies", 82, "High", "Sydney Uni GI DB", "Puffed rice cereal"),
            Entry("cheerios", 74, "High", "Sydney Uni GI DB", "Oat-based cereal"),
            Entry("muesli", 57, "Medium", "Sydney Uni GI DB", "Untoasted natural muesli"),
            Entry("granola", 55, "Medium", "Sydney Uni GI DB", "Toasted granola"),
            Entry("bran flakes", 74, "High", "Sydney Uni GI DB", "Wheat bran flakes"),
            Entry("porridge", 55, "Medium", "Sydney Uni GI DB", "Oat porridge"),
            Entry("instant oatmeal", 79, "High", "Sydney Uni GI DB", "Instant/quick oats"),
            Entry("steel cut oats", 42, "Low", "Sydney Uni GI DB", "Steel-cut/Irish oats"),
            Entry("weetbix", 69, "Medium", "Sydney Uni GI DB", "Weet-Bix wheat biscuit cereal"),
            Entry("weetabix", 74, "High", "Sydney Uni GI DB", "Weetabix cereal"),
            Entry("special k", 56, "Medium", "Sydney Uni GI DB", "Kellogg's Special K"),
            Entry("coco pops", 77, "High", "Estimated", "Chocolate rice puffs cereal", isEstimated: true),
            Entry("all-bran", 42, "Low", "Sydney Uni GI DB", "Kellogg's All-Bran"),
            Entry("nutri-grain", 66, "Medium", "Estimated", "Kellogg's Nutri-Grain", isEstimated: true),
            Entry("oat bran", 44, "Low", "Sydney Uni GI DB", "Oat bran"),

            // ── Indian Staples ──────────────────────────────────────────
            Entry("idli", 77, "High", "Estimated", "Steamed rice cake", isEstimated: true),
            Entry("dosa", 66, "Medium", "Estimated", "Fermented rice-lentil crepe", isEstimated: true),
            Entry("paratha", 55, "Medium", "Estimated", "Layered wheat flatbread", isEstimated: true),
            Entry("biryani", 70, "High", "Estimated", "Spiced rice dish", isEstimated: true),
            Entry("dal", 29, "Low", "Sydney Uni GI DB", "Lentil soup/dal"),
            Entry("samosa", 62, "Medium", "Estimated", "Deep-fried wheat pastry", isEstimated: true),
            Entry("roti", 52, "Low", "Estimated", "Indian whole wheat flatbread", isEstimated: true),
            Entry("upma", 67, "Medium", "Estimated", "Semolina porridge", isEstimated: true),
            Entry("poha", 64, "Medium", "Estimated", "Flattened rice dish", isEstimated: true),

            // ── Latin American ──────────────────────────────────────────
            Entry("arepa", 72, "High", "Estimated", "Corn flour flatbread", isEstimated: true),
            Entry("empanada", 60, "Medium", "Estimated", "Stuffed wheat pastry", isEstimated: true),
            Entry("tamale", 70, "High", "Estimated", "Corn masa tamale", isEstimated: true),
            Entry("pupusa", 65, "Medium", "Estimated", "Stuffed corn tortilla", isEstimated: true),

            // ── African ─────────────────────────────────────────────────
            Entry("fufu", 65, "Medium", "Estimated", "Cassava/plantain fufu", isEstimated: true),
            Entry("injera", 79, "High", "Estimated", "Ethiopian teff flatbread", isEstimated: true),
            Entry("ugali", 68, "Medium", "Estimated", "Cornmeal porridge", isEstimated: true),
            Entry("jollof rice", 72, "High", "Estimated", "West African spiced rice", isEstimated: true),

            // ── Asian ───────────────────────────────────────────────────
            Entry("ramen noodles", 52, "Low", "Estimated", "Instant ramen noodles", isEstimated: true),
            Entry("glass noodles", 39, "Low", "Estimated", "Mung bean glass noodles", isEstimated: true),
            Entry("rice paper", 75, "High", "Estimated", "Rice paper wrappers", isEstimated: true),
            Entry("wonton wrapper", 63, "Medium", "Estimated", "Wheat wonton wrapper", isEstimated: true),
            Entry("dim sum", 58, "Medium", "Estimated", "Steamed dumplings", isEstimated: true),
            Entry("spring roll wrapper", 65, "Medium", "Estimated", "Wheat spring roll wrapper", isEstimated: true),
            Entry("rice pudding", 56, "Medium", "Sydney Uni GI DB", "Rice pudding with milk"),
            Entry("pad thai", 52, "Low", "Estimated", "Thai rice noodle stir-fry", isEstimated: true),
            Entry("fried rice", 72, "High", "Estimated", "Fried rice dish", isEstimated: true),
            Entry("nasi goreng", 72, "High", "Estimated", "Indonesian fried rice", isEstimated: true),
            Entry("pho", 40, "Low", "Estimated", "Vietnamese rice noodle soup", isEstimated: true),

            // ── European ────────────────────────────────────────────────
            Entry("pierogi", 60, "Medium", "Estimated", "Filled wheat dumplings", isEstimated: true),
            Entry("spaetzle", 55, "Medium", "Estimated", "German egg noodle/dumpling", isEstimated: true),
            Entry("carbonara", 49, "Low", "Estimated", "Pasta carbonara", isEstimated: true),

            // ── Middle Eastern ──────────────────────────────────────────
            Entry("pide", 68, "Medium", "Estimated", "Turkish flatbread", isEstimated: true),
            Entry("manakish", 68, "Medium", "Estimated", "Lebanese flatbread", isEstimated: true),
            Entry("tabbouleh", 30, "Low", "Estimated", "Bulgur wheat salad", isEstimated: true),
            Entry("shawarma wrap", 55, "Medium", "Estimated", "Shawarma in wheat wrap", isEstimated: true),
            Entry("kibbeh", 52, "Low", "Estimated", "Bulgur and meat croquette", isEstimated: true),

            // ── Meal items ──────────────────────────────────────────────
            Entry("fish and chips", 63, "Medium", "Estimated", "Battered fish with hot chips", isEstimated: true),
            Entry("chicken nugget", 46, "Low", "Estimated", "Breaded chicken nuggets", isEstimated: true),
            Entry("sausage roll", 60, "Medium", "Estimated", "Puff pastry sausage roll", isEstimated: true),
            Entry("meat pie", 63, "Medium", "Estimated", "Wheat pastry meat pie", isEstimated: true),
            Entry("quiche", 52, "Low", "Estimated", "Egg and pastry quiche", isEstimated: true),

            // ── Meal Replacement & Sports ────────────────────────────────
            Entry("meal replacement", 35, "Low", "Estimated", "Protein-based meal replacement shake", isEstimated: true),
            Entry("protein shake", 30, "Low", "Estimated", "Whey/casein protein shake, varies", isEstimated: true),
            Entry("electrolyte drink", 70, "High", "Estimated", "Sugar-based electrolyte drink", isEstimated: true),

            // ── Vegetables (non-starchy, very low GI) ───────────────────
            Entry("carrot", 39, "Low", "Sydney Uni GI DB", "Boiled carrot"),
            Entry("beetroot", 64, "Medium", "Sydney Uni GI DB", "Boiled beetroot"),
            Entry("pea", 48, "Low", "Sydney Uni GI DB", "Green peas, boiled", regex: new Regex(@"\bpeas?\b", RegexOptions.Compiled | RegexOptions.IgnoreCase)),
            Entry("broccoli", 10, "Low", "Harvard Health", "Non-starchy — negligible glycemic impact"),
            Entry("cauliflower", 10, "Low", "Harvard Health", "Non-starchy — negligible glycemic impact"),
            Entry("spinach", 15, "Low", "Harvard Health", "Non-starchy — negligible glycemic impact"),
            Entry("kale", 15, "Low", "Estimated", "Non-starchy leafy green — negligible glycemic impact", isEstimated: true),
            Entry("zucchini", 15, "Low", "Harvard Health", "Non-starchy — negligible glycemic impact"),
            Entry("courgette", 15, "Low", "Harvard Health", "Non-starchy — same as zucchini"),
            Entry("capsicum", 15, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),
            Entry("bell pepper", 15, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),
            Entry("asparagus", 15, "Low", "Harvard Health", "Non-starchy — negligible glycemic impact"),
            Entry("cabbage", 10, "Low", "Harvard Health", "Non-starchy — negligible glycemic impact"),
            Entry("eggplant", 15, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),
            Entry("aubergine", 15, "Low", "Estimated", "Non-starchy — same as eggplant", isEstimated: true),
            Entry("cucumber", 15, "Low", "Harvard Health", "Non-starchy — negligible glycemic impact"),
            Entry("lettuce", 15, "Low", "Harvard Health", "Non-starchy — negligible glycemic impact"),
            Entry("tomato", 15, "Low", "Sydney Uni GI DB", "Non-starchy — negligible glycemic impact", ["tomato juice", "tomato sauce", "tomato paste"]),
            Entry("celery", 15, "Low", "Harvard Health", "Non-starchy — negligible glycemic impact"),
            Entry("green bean", 20, "Low", "Sydney Uni GI DB", "Green/string beans, boiled"),
            Entry("mushroom", 15, "Low", "Harvard Health", "Non-starchy — negligible glycemic impact"),
            Entry("onion", 10, "Low", "Estimated", "Non-starchy — negligible glycemic impact", ["onion ring"], isEstimated: true),
            Entry("garlic", 10, "Low", "Estimated", "Non-starchy — negligible glycemic impact", ["garlic bread"], isEstimated: true),
            Entry("brussels sprout", 15, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),
            Entry("leek", 15, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),
            Entry("bok choy", 15, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),
            Entry("snow pea", 22, "Low", "Estimated", "Slightly higher carb than most non-starchy veg", isEstimated: true),
            Entry("artichoke", 15, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),
            Entry("fennel", 15, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),
            Entry("radish", 15, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),
            Entry("okra", 20, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),
            Entry("spring onion", 15, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),
            Entry("rocket", 15, "Low", "Estimated", "Non-starchy leafy green — negligible glycemic impact", isEstimated: true),
            Entry("arugula", 15, "Low", "Estimated", "Non-starchy leafy green — negligible glycemic impact", isEstimated: true),
            Entry("swiss chard", 15, "Low", "Estimated", "Non-starchy leafy green — negligible glycemic impact", isEstimated: true),
            Entry("watercress", 15, "Low", "Estimated", "Non-starchy leafy green — negligible glycemic impact", isEstimated: true),
            Entry("endive", 15, "Low", "Estimated", "Non-starchy — negligible glycemic impact", isEstimated: true),

            // ── Nuts & Seeds ────────────────────────────────────────────
            Entry("peanut", 14, "Low", "Sydney Uni GI DB", "Roasted peanuts — very low GI"),
            Entry("almond", 15, "Low", "Estimated", "Raw/roasted almonds — very low GI", isEstimated: true),
            Entry("cashew", 22, "Low", "Estimated", "Roasted cashews", isEstimated: true),
            Entry("walnut", 15, "Low", "Estimated", "Raw walnuts — very low GI", isEstimated: true),
            Entry("pecan", 10, "Low", "Estimated", "Raw pecans — very low GI", isEstimated: true),
            Entry("macadamia", 10, "Low", "Estimated", "Raw macadamias — very low GI", isEstimated: true),
            Entry("hazelnut", 15, "Low", "Estimated", "Raw hazelnuts — very low GI", isEstimated: true),
            Entry("pistachio", 15, "Low", "Estimated", "Roasted pistachios — very low GI", isEstimated: true),
            Entry("sunflower seed", 35, "Low", "Estimated", "Sunflower kernels", isEstimated: true),
            Entry("pumpkin seed", 25, "Low", "Estimated", "Pepitas/pumpkin seeds", isEstimated: true),
            Entry("chia seed", 1, "Low", "Estimated", "Chia seeds — negligible GI", isEstimated: true),
            Entry("flax seed", 32, "Low", "Estimated", "Flaxseed/linseed", isEstimated: true),
            Entry("sesame seed", 35, "Low", "Estimated", "Sesame seeds", isEstimated: true),
            Entry("pine nut", 15, "Low", "Estimated", "Pine nuts — very low GI", isEstimated: true),
            Entry("brazil nut", 10, "Low", "Estimated", "Brazil nuts — very low GI", isEstimated: true),
            Entry("hemp seed", 15, "Low", "Estimated", "Hemp hearts — very low GI", isEstimated: true),
            Entry("peanut butter", 14, "Low", "Sydney Uni GI DB", "Natural peanut butter"),
            Entry("almond butter", 15, "Low", "Estimated", "Natural almond butter", isEstimated: true),
            Entry("tahini", 35, "Low", "Estimated", "Sesame seed paste", isEstimated: true),

            // ── Proteins (negligible carbohydrate) ──────────────────────
            Entry("tofu", 15, "Low", "Estimated", "Firm tofu — negligible carb content", isEstimated: true),
            Entry("tempeh", 15, "Low", "Estimated", "Fermented soybean cake — low carb", isEstimated: true),
            Entry("egg", 0, "Low", "Harvard Health", "Negligible carbohydrate — GI not applicable", ["eggplant"]),
            Entry("chicken breast", 0, "Low", "Estimated", "Negligible carbohydrate — GI not applicable", isEstimated: true),
            Entry("chicken", 0, "Low", "Estimated", "Negligible carbohydrate — GI not applicable", ["chicken breast", "chicken nugget"], isEstimated: true),
            Entry("salmon", 0, "Low", "Estimated", "Negligible carbohydrate — GI not applicable", isEstimated: true),
            Entry("tuna", 0, "Low", "Estimated", "Negligible carbohydrate — GI not applicable", isEstimated: true),
            Entry("beef", 0, "Low", "Estimated", "Negligible carbohydrate — GI not applicable", isEstimated: true),
            Entry("lamb", 0, "Low", "Estimated", "Negligible carbohydrate — GI not applicable", isEstimated: true),
            Entry("pork", 0, "Low", "Estimated", "Negligible carbohydrate — GI not applicable", isEstimated: true),
            Entry("turkey", 0, "Low", "Estimated", "Negligible carbohydrate — GI not applicable", isEstimated: true),
            Entry("shrimp", 0, "Low", "Estimated", "Negligible carbohydrate — GI not applicable", isEstimated: true),
            Entry("prawn", 0, "Low", "Estimated", "Negligible carbohydrate — GI not applicable", isEstimated: true),
            Entry("fish", 0, "Low", "Estimated", "Negligible carbohydrate — GI not applicable", ["fish and chips", "fish cake", "fish finger", "fish sauce", "swordfish", "jellyfish", "starfish", "cuttlefish"], isEstimated: true),
        };

        // Sort by pattern length descending — longest matches first
        GiDatabase = entries.OrderByDescending(e => e.Pattern.Length).ToArray();
    }

    static GiEntry Entry(string pattern, int gi, string category, string source, string notes, string[]? exclusions = null, Regex? regex = null, bool isEstimated = false)
    {
        regex ??= new Regex(@"\b" + Regex.Escape(pattern) + @"\b", RegexOptions.Compiled | RegexOptions.IgnoreCase);
        return new GiEntry(pattern, regex, gi, category, source, notes, exclusions, isEstimated);
    }
}
