using System.Text.RegularExpressions;

namespace GutAI.Infrastructure.Services;

internal static class GutRiskData
{
    internal record AdditiveInfo(string ENumber, string Name, string Category, string RiskLevel, string Explanation);
    internal record IngredientRiskEntry(string Pattern, Regex? Regex, AdditiveInfo Info);

    internal enum TriggerType { Fodmap, Additive, Processing, Nutrient, Combination }
    internal enum FodmapClass { None, Fructans, GOS, Lactose, ExcessFructose, Polyols }
    internal enum DoseSensitivity { Low, Medium, High }

    internal static readonly IReadOnlyDictionary<string, (TriggerType Trigger, FodmapClass Fodmap)> CategoryMap =
        new Dictionary<string, (TriggerType, FodmapClass)>
        {
            ["Sugar Alcohol"] = (TriggerType.Fodmap, FodmapClass.Polyols),
            ["Polyol Source"] = (TriggerType.Fodmap, FodmapClass.Polyols),
            ["High-FODMAP Ingredient"] = (TriggerType.Fodmap, FodmapClass.Fructans),
            ["Prebiotic Fiber (FODMAP)"] = (TriggerType.Fodmap, FodmapClass.Fructans),
            ["Dairy/Lactose"] = (TriggerType.Fodmap, FodmapClass.Lactose),
            ["Fructose Source"] = (TriggerType.Fodmap, FodmapClass.ExcessFructose),
            ["Sweetener"] = (TriggerType.Fodmap, FodmapClass.ExcessFructose),
            ["GOS Source"] = (TriggerType.Fodmap, FodmapClass.GOS),
            ["Emulsifier"] = (TriggerType.Additive, FodmapClass.None),
            ["Emulsifier/Thickener"] = (TriggerType.Additive, FodmapClass.None),
            ["Thickener"] = (TriggerType.Additive, FodmapClass.None),
            ["Preservative"] = (TriggerType.Additive, FodmapClass.None),
            ["Preservative/Sulfite"] = (TriggerType.Additive, FodmapClass.None),
            ["Artificial Sweetener"] = (TriggerType.Additive, FodmapClass.None),
            ["Artificial Colorant"] = (TriggerType.Additive, FodmapClass.None),
            ["Colorant"] = (TriggerType.Additive, FodmapClass.None),
            ["Colorant/Whitener"] = (TriggerType.Additive, FodmapClass.None),
            ["Antioxidant"] = (TriggerType.Additive, FodmapClass.None),
            ["Acidity Regulator"] = (TriggerType.Additive, FodmapClass.None),
            ["Flavor Enhancer"] = (TriggerType.Additive, FodmapClass.None),
            ["Anti-caking Agent"] = (TriggerType.Additive, FodmapClass.None),
            ["Emulsifier/Stabilizer"] = (TriggerType.Additive, FodmapClass.None),
            ["Stabilizer"] = (TriggerType.Additive, FodmapClass.None),
            ["Bulking Agent"] = (TriggerType.Additive, FodmapClass.None),
            ["Processing Level"] = (TriggerType.Processing, FodmapClass.None),
            ["Nutrient Concern"] = (TriggerType.Nutrient, FodmapClass.None),
            ["Stacking Penalty"] = (TriggerType.Combination, FodmapClass.None),
            ["Stimulant/Motility"] = (TriggerType.Additive, FodmapClass.None),
            ["Spicy/Irritant"] = (TriggerType.Additive, FodmapClass.None),
            ["Alcohol & Fermented"] = (TriggerType.Additive, FodmapClass.None),
            ["Hidden FODMAP Risk"] = (TriggerType.Fodmap, FodmapClass.Fructans),
        };

    internal static readonly IReadOnlyDictionary<string, AdditiveInfo> GutHarmfulAdditives =
        new Dictionary<string, AdditiveInfo>(StringComparer.OrdinalIgnoreCase)
        {
            // ── Emulsifiers (damage mucus layer, increase intestinal permeability) ──
            ["E433"] = new("E433", "Polysorbate 80", "Emulsifier", "High",
            "Some research, primarily in animal models, suggests potential effects on the gut mucus layer and intestinal inflammation. Human evidence is still evolving."),
            ["E466"] = new("E466", "Carboxymethyl Cellulose (CMC)", "Emulsifier", "High",
            "Some studies have explored potential effects on the gut mucus barrier and bacterial balance. Research is ongoing."),
            ["E471"] = new("E471", "Mono- and Diglycerides", "Emulsifier", "Medium",
            "Common emulsifier that may affect gut barrier integrity at high intake levels."),
            ["E472E"] = new("E472E", "DATEM", "Emulsifier", "Medium",
            "Diacetyl tartaric acid ester used in bread — may affect gut microbiome composition."),
            ["E435"] = new("E435", "Polysorbate 60", "Emulsifier", "Medium",
            "Similar mechanism to Polysorbate 80 but less studied. May damage gut mucus layer."),
            ["E436"] = new("E436", "Polysorbate 65", "Emulsifier", "Medium",
            "Polysorbate family emulsifier with potential gut mucus disruption."),
            ["E407"] = new("E407", "Carrageenan", "Emulsifier/Thickener", "High",
            "Has been studied for potential gut effects. Some animal research has explored its role in intestinal inflammation, though human relevance is debated."),
            ["E407A"] = new("E407A", "Processed Eucheuma Seaweed (PES)", "Emulsifier/Thickener", "High",
            "Semi-refined carrageenan — studied for similar potential effects as E407."),
            ["E415"] = new("E415", "Xanthan Gum", "Thickener", "Low",
            "Generally well-tolerated but can cause bloating and gas in high amounts, especially in people with SIBO."),
            ["E410"] = new("E410", "Locust Bean Gum", "Thickener", "Low",
            "Generally well-tolerated; may cause mild bloating in sensitive individuals at high doses."),
            ["E412"] = new("E412", "Guar Gum", "Thickener", "Low",
            "Fermentable fiber that can cause gas and bloating, especially in large amounts or with SIBO."),
            ["E417"] = new("E417", "Tara Gum", "Thickener", "Low",
            "Similar to guar gum; may cause mild GI discomfort in sensitive individuals."),
            ["E418"] = new("E418", "Gellan Gum", "Thickener", "Low",
            "Generally well-tolerated but may cause bloating at high intake in sensitive individuals."),
            ["E440"] = new("E440", "Pectin", "Thickener", "Low",
            "Naturally occurring in fruit; fermentable fiber that may cause gas in large supplemental doses."),

            // ── Alginates & Additional Hydrocolloids ──
            ["E401"] = new("E401", "Sodium Alginate", "Thickener", "Low",
            "Seaweed-derived hydrocolloid; generally well-tolerated but fermentable — may cause gas and bloating in sensitive individuals."),
            ["E402"] = new("E402", "Potassium Alginate", "Thickener", "Low",
            "Alginate salt; similar gut profile to sodium alginate."),
            ["E403"] = new("E403", "Ammonium Alginate", "Thickener", "Low",
            "Alginate salt; similar gut profile to sodium alginate."),
            ["E404"] = new("E404", "Calcium Alginate", "Thickener", "Low",
            "Alginate salt; similar gut profile to sodium alginate."),
            ["E405"] = new("E405", "Propylene Glycol Alginate", "Thickener", "Low",
            "Modified alginate ester; generally well-tolerated at typical food levels."),
            ["E413"] = new("E413", "Tragacanth", "Thickener", "Low",
            "Natural gum; may cause bloating and gas in sensitive individuals due to fermentable fiber content."),
            ["E414"] = new("E414", "Gum Arabic", "Thickener", "Low",
            "Highly fermentable soluble fiber; generally well-tolerated but may cause gas at high doses."),

            // ── Sugar Alcohols (high FODMAP — osmotic diarrhea, bloating, gas) ──
            ["E420"] = new("E420", "Sorbitol", "Sugar Alcohol", "High",
            "High-FODMAP polyol. Poorly absorbed, draws water into the intestine which may cause bloating, cramps, and diarrhea. Frequently reported as a source of discomfort for FODMAP-sensitive individuals."),
            ["E421"] = new("E421", "Mannitol", "Sugar Alcohol", "High",
            "High-FODMAP polyol. May cause significant bloating and diarrhea, particularly at higher doses (>0.5g)."),
            ["E953"] = new("E953", "Isomalt", "Sugar Alcohol", "High",
            "High-FODMAP. May cause dose-dependent GI distress — bloating, flatulence, and diarrhea."),
            ["E965"] = new("E965", "Maltitol", "Sugar Alcohol", "High",
            "High-FODMAP. One of the less well-tolerated sugar alcohols. May cause bloating and diarrhea, particularly at higher doses."),
            ["E967"] = new("E967", "Xylitol", "Sugar Alcohol", "High",
            "FODMAP polyol that may cause bloating, gas, and diarrhea. Dose-dependent — symptoms commonly reported above 10g."),
            ["E968"] = new("E968", "Erythritol", "Sugar Alcohol", "Low",
            "Best-tolerated sugar alcohol (90% absorbed in small intestine), but can still cause nausea and bloating at high doses."),
            ["E966"] = new("E966", "Lactitol", "Sugar Alcohol", "High",
            "Poorly absorbed polyol that causes dose-dependent bloating and osmotic diarrhea."),

            // ── Artificial Sweeteners (microbiome disruption) ──
            ["E951"] = new("E951", "Aspartame", "Artificial Sweetener", "Medium",
            "Some evidence suggests aspartame may alter gut microbiome composition; clinical significance in humans is still under investigation."),
            ["E950"] = new("E950", "Acesulfame K", "Artificial Sweetener", "Medium",
            "Animal studies show altered gut microbiome, including reduced Bifidobacterium; human data are limited."),
            ["E955"] = new("E955", "Sucralose", "Artificial Sweetener", "Medium",
            "Animal studies report reduced beneficial gut bacteria at high doses; human studies show mixed results at typical intake levels."),
            ["E954"] = new("E954", "Saccharin", "Artificial Sweetener", "Medium",
            "Shown in some studies to alter gut microbiome and glucose metabolism; effects may vary between individuals."),
            ["E962"] = new("E962", "Aspartame-Acesulfame Salt", "Artificial Sweetener", "Medium",
            "Combination sweetener with combined microbiome-disrupting effects of both components."),

            // ── Preservatives (antimicrobial = kills good bacteria too) ──
            ["E211"] = new("E211", "Sodium Benzoate", "Preservative", "Medium",
            "Antimicrobial preservative that can also reduce beneficial gut bacteria. May worsen histamine intolerance symptoms."),
            ["E210"] = new("E210", "Benzoic Acid", "Preservative", "Medium",
            "Antimicrobial preservative; parent compound of sodium benzoate with similar gut flora effects."),
            ["E200"] = new("E200", "Sorbic Acid", "Preservative", "Low",
            "Antimicrobial preservative that may modestly affect gut flora at high intake levels."),
            ["E202"] = new("E202", "Potassium Sorbate", "Preservative", "Low",
            "Generally safe but has antimicrobial properties that may modestly affect gut flora at high intake."),
            ["E220"] = new("E220", "Sulfur Dioxide", "Preservative/Sulfite", "Medium",
            "Sulfite that can trigger GI symptoms in sensitive individuals, especially those with sulfite sensitivity or asthma."),
            ["E221"] = new("E221", "Sodium Sulfite", "Preservative/Sulfite", "Medium",
            "Sulfite preservative — can cause abdominal pain, diarrhea, and nausea in sulfite-sensitive individuals."),
            ["E223"] = new("E223", "Sodium Metabisulfite", "Preservative/Sulfite", "Medium",
            "Sulfite preservative used in dried fruits and wine. Common trigger for GI symptoms in sensitive people."),
            ["E250"] = new("E250", "Sodium Nitrite", "Preservative", "Medium",
            "Used in processed meats. Some research has explored potential links to intestinal changes and nitrosamine formation."),
            ["E252"] = new("E252", "Potassium Nitrate", "Preservative", "Medium",
            "Converts to nitrite in the body. Similar gut inflammation concerns as E250."),

            // ── Colorants (some linked to gut inflammation) ──
            ["E102"] = new("E102", "Tartrazine", "Artificial Colorant", "Low",
            "Azo dye that may increase intestinal permeability and trigger symptoms in sensitive individuals."),
            ["E110"] = new("E110", "Sunset Yellow", "Artificial Colorant", "Low",
            "Azo dye associated with increased intestinal permeability in some studies."),
            ["E129"] = new("E129", "Allura Red AC", "Artificial Colorant", "Medium",
            "Some animal studies have explored potential effects on intestinal inflammation."),
            ["E171"] = new("E171", "Titanium Dioxide", "Colorant/Whitener", "High",
            "Some research has raised concerns about nanoparticle accumulation and potential gut effects. Banned in the EU since 2022."),

            // ── Phosphate Additives (gut & kidney stress) ──
            ["E338"] = new("E338", "Phosphoric Acid", "Acidity Regulator", "Low",
            "Common in soft drinks. May affect gut microbiome and calcium absorption at high intake levels."),
            ["E339"] = new("E339", "Sodium Phosphates", "Emulsifier/Stabilizer", "Low",
            "Inorganic phosphate — high intake linked to gut inflammation and cardiovascular risk."),
            ["E341"] = new("E341", "Calcium Phosphates", "Stabilizer", "Low",
            "Inorganic phosphate additive with similar concerns to E339 at high intake."),
            ["E450"] = new("E450", "Diphosphates", "Emulsifier/Stabilizer", "Low",
            "Phosphate additive; excessive inorganic phosphate intake is linked to gut and vascular inflammation."),
            ["E451"] = new("E451", "Triphosphates", "Emulsifier/Stabilizer", "Low",
            "Phosphate additive with similar concerns to E450 regarding cumulative phosphate load."),
            ["E452"] = new("E452", "Polyphosphates", "Emulsifier/Stabilizer", "Low",
            "Phosphate additive; contributes to total inorganic phosphate burden."),

            // ── Acidity Regulators ──
            ["E330"] = new("E330", "Citric Acid (manufactured)", "Acidity Regulator", "Low",
            "Industrially produced citric acid (from Aspergillus niger) may trigger symptoms in a small subset of sensitive individuals."),
            ["E296"] = new("E296", "Malic Acid", "Acidity Regulator", "Low",
            "Generally well-tolerated; may contribute to GI discomfort at very high doses."),
            ["E260"] = new("E260", "Acetic Acid", "Acidity Regulator", "Low",
            "Generally well-tolerated; found naturally in vinegar."),
            ["E262"] = new("E262", "Sodium Acetate", "Acidity Regulator", "Low",
            "Generally well-tolerated acidity regulator."),
            ["E270"] = new("E270", "Lactic Acid", "Acidity Regulator", "Low",
            "Generally well-tolerated; occurs naturally in fermented foods."),

            // ── Antioxidants ──
            ["E319"] = new("E319", "TBHQ", "Antioxidant", "Medium",
            "Tertiary butylhydroquinone — some animal studies suggest immune and gut microbiome effects at high doses."),
            ["E320"] = new("E320", "BHA", "Antioxidant", "Medium",
            "Butylated hydroxyanisole — possible endocrine disruptor; some evidence of gut microbiome effects."),
            ["E321"] = new("E321", "BHT", "Antioxidant", "Low",
            "Butylated hydroxytoluene — generally considered safe at typical food levels; limited gut-specific concerns."),

            // ── Other Gut Irritants ──
            ["E621"] = new("E621", "Monosodium Glutamate (MSG)", "Flavor Enhancer", "Low",
            "Generally safe but may cause GI symptoms in a small subset of sensitive individuals (\"Chinese Restaurant Syndrome\")."),
            ["E551"] = new("E551", "Silicon Dioxide", "Anti-caking Agent", "Low",
            "Nanoparticle form may affect gut barrier function; standard forms are generally considered safe."),

            // ── Lecithins ──
            ["E322"] = new("E322", "Lecithins", "Emulsifier", "Low",
            "Generally well-tolerated; soy-derived lecithin may be a concern for soy-sensitive individuals."),

            // ── Missing Artificial Sweeteners ──
            ["E952"] = new("E952", "Cyclamate", "Artificial Sweetener", "Medium",
            "Artificial sweetener banned in the US. Some evidence of gut microbiome disruption."),
            ["E961"] = new("E961", "Neotame", "Artificial Sweetener", "Medium",
            "Potent artificial sweetener. Limited data on gut effects; structural similarity to aspartame suggests potential microbiome impact."),
            ["E969"] = new("E969", "Advantame", "Artificial Sweetener", "Medium",
            "Ultra-potent artificial sweetener. Limited human data on gut microbiome effects."),

            // ── Missing Additives ──
            ["E422"] = new("E422", "Glycerol", "Bulking Agent", "Low",
            "Osmotic laxative effect at high doses. May draw water into the intestine causing loose stools."),
            ["E476"] = new("E476", "PGPR", "Emulsifier", "Low",
            "Polyglycerol polyricinoleate — common in chocolate. May affect gut barrier at high intake levels."),
            ["E491"] = new("E491", "Sorbitan Monostearate", "Emulsifier", "Low",
            "Sorbitan ester emulsifier. May affect gut barrier integrity at high intake levels."),
            ["E492"] = new("E492", "Sorbitan Tristearate", "Emulsifier", "Low",
            "Sorbitan ester emulsifier used in confectionery. May affect gut barrier integrity."),
            ["E493"] = new("E493", "Sorbitan Monolaurate", "Emulsifier", "Low",
            "Sorbitan ester emulsifier. May affect gut barrier integrity at high intake levels."),
            ["E494"] = new("E494", "Sorbitan Monooleate", "Emulsifier", "Low",
            "Sorbitan ester emulsifier. May affect gut barrier integrity at high intake levels."),
            ["E495"] = new("E495", "Sorbitan Monopalmitate", "Emulsifier", "Low",
            "Sorbitan ester emulsifier. May affect gut barrier integrity at high intake levels."),
            ["E481"] = new("E481", "Sodium Stearoyl Lactylate", "Emulsifier", "Low",
            "Stearoyl lactylate bread emulsifier. May affect gut barrier at high intake."),
            ["E482"] = new("E482", "Calcium Stearoyl Lactylate", "Emulsifier", "Low",
            "Stearoyl lactylate bread emulsifier. May affect gut barrier at high intake."),
            ["E1442"] = new("E1442", "Hydroxypropyl Distarch Phosphate", "Thickener", "Low",
            "Modified starch. May resist digestion and undergo colonic fermentation, causing gas in sensitive individuals."),
            ["E1404"] = new("E1404", "Oxidised Starch", "Thickener", "Low",
            "Modified starch. May resist digestion and cause gas in sensitive individuals."),
            ["E1412"] = new("E1412", "Distarch Phosphate", "Thickener", "Low",
            "Modified starch. May resist digestion and undergo colonic fermentation, causing gas in sensitive individuals."),
            ["E1414"] = new("E1414", "Acetylated Distarch Phosphate", "Thickener", "Low",
            "Modified starch. Resists digestion, potentially causing gas and bloating via colonic fermentation."),
            ["E1420"] = new("E1420", "Acetylated Starch", "Thickener", "Low",
            "Modified starch. May resist digestion and cause gas in sensitive individuals."),
            ["E1450"] = new("E1450", "Starch Sodium Octenyl Succinate", "Thickener", "Low",
            "Modified starch used as emulsifier. May resist digestion and cause gas in sensitive individuals."),
            ["E331"] = new("E331", "Sodium Citrates", "Acidity Regulator", "Low",
            "Generally well-tolerated acidity regulator. May contribute to GI discomfort at very high doses."),
            ["E334"] = new("E334", "Tartaric Acid", "Acidity Regulator", "Low",
            "Naturally occurring acid. Generally well-tolerated; may cause GI discomfort at high doses."),
            ["E224"] = new("E224", "Potassium Metabisulfite", "Preservative/Sulfite", "Medium",
            "Sulfite preservative. Can trigger GI symptoms in sulfite-sensitive individuals."),

            // ── Additional Emulsifiers ──
            ["E432"] = new("E432", "Polysorbate 20", "Emulsifier", "Medium",
            "Polysorbate family emulsifier with potential gut mucus disruption."),
            ["E434"] = new("E434", "Polysorbate 40", "Emulsifier", "Medium",
            "Polysorbate family emulsifier with potential gut mucus disruption."),
            ["E473"] = new("E473", "Sucrose Esters of Fatty Acids", "Emulsifier", "Low",
            "Emulsifier used in bakery products. May affect gut barrier at high intake."),
            ["E474"] = new("E474", "Sucroglycerides", "Emulsifier", "Low",
            "Emulsifier derived from sucrose esters. May affect gut barrier at high intake."),
            ["E475"] = new("E475", "Polyglycerol Esters of Fatty Acids", "Emulsifier", "Low",
            "Emulsifier used in bakery and confectionery. May affect gut barrier integrity."),

            // ── Additional Preservatives ──
            ["E212"] = new("E212", "Potassium Benzoate", "Preservative", "Medium",
            "Antimicrobial preservative — similar gut flora effects to sodium benzoate."),
            ["E213"] = new("E213", "Calcium Benzoate", "Preservative", "Medium",
            "Antimicrobial preservative — similar gut flora effects to sodium benzoate."),
            ["E222"] = new("E222", "Sodium Hydrogen Sulfite", "Preservative/Sulfite", "Medium",
            "Sulfite preservative used in wine. Can trigger GI symptoms in sulfite-sensitive individuals."),
            ["E226"] = new("E226", "Calcium Sulfite", "Preservative/Sulfite", "Medium",
            "Sulfite preservative — can trigger GI symptoms in sulfite-sensitive individuals."),
            ["E227"] = new("E227", "Calcium Hydrogen Sulfite", "Preservative/Sulfite", "Medium",
            "Sulfite preservative — can trigger GI symptoms in sulfite-sensitive individuals."),
            ["E228"] = new("E228", "Potassium Hydrogen Sulfite", "Preservative/Sulfite", "Medium",
            "Sulfite preservative — can trigger GI symptoms in sulfite-sensitive individuals."),
            ["E234"] = new("E234", "Nisin", "Preservative", "Low",
            "Natural antimicrobial peptide. May modestly affect gut flora at high doses."),
            ["E235"] = new("E235", "Natamycin", "Preservative", "Low",
            "Antifungal used on cheese surfaces. Limited gut absorption at typical exposure levels."),
            ["E249"] = new("E249", "Potassium Nitrite", "Preservative", "Medium",
            "Nitrite preservative used in processed meats — similar concerns to E250."),
            ["E251"] = new("E251", "Sodium Nitrate", "Preservative", "Medium",
            "Converts to nitrite in the body. Similar gut concerns as E252."),

            // ── Additional Colorants ──
            ["E104"] = new("E104", "Quinoline Yellow", "Artificial Colorant", "Low",
            "Azo dye that may increase intestinal permeability in sensitive individuals."),
            ["E122"] = new("E122", "Carmoisine/Azorubine", "Artificial Colorant", "Low",
            "Azo dye associated with increased intestinal permeability in some studies."),
            ["E124"] = new("E124", "Ponceau 4R", "Artificial Colorant", "Low",
            "Azo dye that may increase intestinal permeability in sensitive individuals."),
            ["E127"] = new("E127", "Erythrosine", "Artificial Colorant", "Low",
            "May affect thyroid function and gut microbiome at high doses."),
            ["E131"] = new("E131", "Patent Blue V", "Artificial Colorant", "Low",
            "Synthetic colorant with limited gut-specific data."),
            ["E132"] = new("E132", "Indigo Carmine", "Artificial Colorant", "Low",
            "Synthetic colorant — limited gut-specific data but possible in sensitive individuals."),
            ["E133"] = new("E133", "Brilliant Blue FCF", "Artificial Colorant", "Low",
            "Blue 1 — may increase intestinal permeability at high doses in animal models."),
            ["E142"] = new("E142", "Green S", "Artificial Colorant", "Low",
            "Synthetic green colorant — limited gut-specific data."),
            ["E150C"] = new("E150C", "Ammonia Caramel", "Colorant", "Low",
            "Caramel coloring containing 4-MEI — some concern about intestinal effects at high intake."),
            ["E150D"] = new("E150D", "Sulfite Ammonia Caramel", "Colorant", "Low",
            "Most common caramel coloring (cola). Contains 4-MEI — possible intestinal concern at high intake."),
            ["E160B"] = new("E160B", "Annatto", "Colorant", "Low",
            "Natural colorant — may trigger symptoms in a small subset of sensitive individuals."),

            // ── Additional Sweeteners ──
            ["E960"] = new("E960", "Steviol Glycosides (Stevia)", "Sweetener", "Low",
            "Natural sweetener. Generally well-tolerated but some individuals report bloating."),
            ["E964"] = new("E964", "Polyglycitol Syrup", "Sugar Alcohol", "High",
            "Mixture of sugar alcohols — high FODMAP. Causes bloating and osmotic diarrhea."),

            // ── Additional Modified Starches ──
            ["E1410"] = new("E1410", "Monostarch Phosphate", "Thickener", "Low",
            "Modified starch. May resist digestion and cause gas in sensitive individuals."),
            ["E1413"] = new("E1413", "Phosphated Distarch Phosphate", "Thickener", "Low",
            "Modified starch — may resist digestion and undergo colonic fermentation."),
            ["E1422"] = new("E1422", "Acetylated Distarch Adipate", "Thickener", "Low",
            "Modified starch used in sauces. May resist digestion and cause gas."),
            ["E1440"] = new("E1440", "Hydroxypropyl Starch", "Thickener", "Low",
            "Modified starch. May resist digestion causing gas."),
            ["E1451"] = new("E1451", "Acetylated Oxidised Starch", "Thickener", "Low",
            "Modified starch. May resist digestion causing gas in sensitive individuals."),

            // ── Other Relevant Additives ──
            ["E461"] = new("E461", "Methyl Cellulose", "Thickener", "Low",
            "Non-fermentable fiber. Generally well-tolerated; osmotic effect at very high doses."),
            ["E460"] = new("E460", "Cellulose", "Bulking Agent", "Low",
            "Microcrystalline cellulose — inert fiber, generally well-tolerated."),
            ["E463"] = new("E463", "Hydroxypropyl Cellulose", "Thickener", "Low",
            "Modified cellulose — generally well-tolerated."),
            ["E464"] = new("E464", "Hydroxypropyl Methyl Cellulose (HPMC)", "Thickener", "Low",
            "Used in gluten-free bread. Generally well-tolerated."),
            ["E500"] = new("E500", "Sodium Carbonates", "Acidity Regulator", "Low",
            "Baking soda. Generally well-tolerated; excess may cause GI disturbance."),
            ["E508"] = new("E508", "Potassium Chloride", "Flavor Enhancer", "Low",
            "Salt substitute. May cause GI irritation at high doses."),
            ["E570"] = new("E570", "Stearic Acid", "Emulsifier", "Low",
            "Fatty acid used as emulsifier. Generally well-tolerated."),
        };

    internal static readonly string[] SugarAlcoholNames =
    [
        "sorbitol", "mannitol", "xylitol", "maltitol", "isomalt", "erythritol",
        "lactitol", "hydrogenated starch hydrolysate", "polyol",
    ];

    internal static readonly string[] ArtificialSweetenerNames =
    [
        "aspartame", "sucralose", "saccharin", "acesulfame", "neotame",
        "advantame", "cyclamate",
    ];

    internal static readonly IReadOnlyList<IngredientRiskEntry> IngredientPatterns =
    [
        new("carrageenan", null, new("E407", "Carrageenan", "Emulsifier/Thickener", "High",
            "Triggers intestinal inflammation. Used in research to induce gut inflammation.")),
        new("polysorbate 80", null, new("E433", "Polysorbate 80", "Emulsifier", "High",
            "Damages gut mucus layer and promotes intestinal inflammation.")),
        new("polysorbate 60", null, new("E435", "Polysorbate 60", "Emulsifier", "Medium",
            "May damage gut mucus layer.")),
        new("cellulose gum", null, new("E466", "Carboxymethyl Cellulose", "Emulsifier", "High",
            "Erodes protective gut mucus barrier.")),
        new("carboxymethyl cellulose", null, new("E466", "Carboxymethyl Cellulose", "Emulsifier", "High",
            "Erodes protective gut mucus barrier.")),
        new("locust bean gum", null, new("E410", "Locust Bean Gum", "Thickener", "Low",
            "Generally well-tolerated; may cause mild bloating in sensitive individuals.")),
        new("guar gum", null, new("E412", "Guar Gum", "Thickener", "Low",
            "Fermentable fiber that can cause gas and bloating, especially in large amounts.")),
        new("tara gum", null, new("E417", "Tara Gum", "Thickener", "Low",
            "Similar to guar gum; may cause mild GI discomfort in sensitive individuals.")),
        new("gellan gum", null, new("E418", "Gellan Gum", "Thickener", "Low",
            "Generally well-tolerated but may cause bloating at high intake.")),
        new("xanthan gum", null, new("E415", "Xanthan Gum", "Thickener", "Low",
            "Fermentable polysaccharide; may cause gas and bloating in sensitive individuals.")),
        new("pectin", null, new("E440", "Pectin", "Thickener", "Low",
            "Naturally occurring in fruit; may cause gas in large supplemental doses.")),
        new("sodium benzoate", null, new("E211", "Sodium Benzoate", "Preservative", "Medium",
            "Antimicrobial that can also reduce beneficial gut bacteria.")),
        new("benzoic acid", null, new("E210", "Benzoic Acid", "Preservative", "Medium",
            "Antimicrobial preservative with gut flora effects.")),
        new("sorbic acid", null, new("E200", "Sorbic Acid", "Preservative", "Low",
            "Antimicrobial preservative that may modestly affect gut flora.")),
        new("titanium dioxide", null, new("E171", "Titanium Dioxide", "Colorant", "High",
            "Nanoparticles disrupt microbiome and promote gut inflammation.")),
        new("tbhq", new Regex(@"\btbhq\b", RegexOptions.Compiled), new("E319", "TBHQ", "Antioxidant", "Medium",
            "Some animal studies suggest immune and gut microbiome effects.")),
        new("bha", new Regex(@"\bbha\b", RegexOptions.Compiled), new("E320", "BHA", "Antioxidant", "Medium",
            "Butylated hydroxyanisole — possible endocrine disruptor with gut effects.")),
        new("bht", new Regex(@"\bbht\b", RegexOptions.Compiled), new("E321", "BHT", "Antioxidant", "Low",
            "Butylated hydroxytoluene — limited gut-specific concerns at typical levels.")),
        new("polydextrose", null, new("", "Polydextrose", "Bulking Agent", "Low",
            "Soluble fiber that can cause gas and bloating at high doses (>50g/day).")),
        new("sorbitol", null, new("E420", "Sorbitol", "Sugar Alcohol", "High",
            "High-FODMAP polyol causing bloating, cramps, and diarrhea.")),
        new("mannitol", null, new("E421", "Mannitol", "Sugar Alcohol", "High",
            "High-FODMAP polyol causing significant GI distress.")),
        new("maltitol", null, new("E965", "Maltitol", "Sugar Alcohol", "High",
            "High-FODMAP. Causes severe bloating and diarrhea.")),
        new("xylitol", null, new("E967", "Xylitol", "Sugar Alcohol", "High",
            "FODMAP polyol causing bloating and gas.")),
        new("isomalt", null, new("E953", "Isomalt", "Sugar Alcohol", "High",
            "High-FODMAP causing dose-dependent GI distress.")),
        new("lactitol", null, new("E966", "Lactitol", "Sugar Alcohol", "High",
            "Poorly absorbed polyol causing bloating and osmotic diarrhea.")),
        new("erythritol", null, new("E968", "Erythritol", "Sugar Alcohol", "Low",
            "Better tolerated polyol but may cause GI symptoms at high doses.")),
        new("sugar alcohol", null, new("", "Sugar Alcohol", "Sugar Alcohol", "High",
            "Sugar alcohols are high-FODMAP and can cause bloating, gas, and diarrhea in sensitive individuals.")),
        new("sucralose", null, new("E955", "Sucralose", "Artificial Sweetener", "Medium",
            "Animal studies report reduced beneficial gut bacteria at high doses.")),
        new("aspartame", null, new("E951", "Aspartame", "Artificial Sweetener", "Medium",
            "Some evidence suggests altered gut microbiome; human significance under investigation.")),
        new("acesulfame", null, new("E950", "Acesulfame K", "Artificial Sweetener", "Medium",
            "Animal studies show reduced beneficial Bifidobacterium; human data limited.")),
        new("saccharin", null, new("E954", "Saccharin", "Artificial Sweetener", "Medium",
            "Some studies show altered gut microbiome and glucose metabolism.")),
        new("sodium nitrite", null, new("E250", "Sodium Nitrite", "Preservative", "Medium",
            "Associated with increased intestinal inflammation.")),
        new("allura red", null, new("E129", "Allura Red AC", "Artificial Colorant", "Medium",
            "Promotes intestinal inflammation and colitis susceptibility.")),
        new("red 40", null, new("E129", "Allura Red AC", "Artificial Colorant", "Medium",
            "Promotes intestinal inflammation and colitis susceptibility.")),
        new("soy lecithin", null, new("E322", "Lecithins", "Emulsifier", "Low",
            "Generally well-tolerated; soy-derived lecithin may be a concern for soy-sensitive individuals.")),
        new("lecithin", null, new("E322", "Lecithins", "Emulsifier", "Low",
            "Generally well-tolerated; soy-derived lecithin may be a concern for soy-sensitive individuals.")),
        new("onion powder", null, new("", "Onion Powder", "High-FODMAP Ingredient", "High",
            "Concentrated source of fructans (high-FODMAP). Common IBS trigger even in small amounts.")),
        new("garlic powder", null, new("", "Garlic Powder", "High-FODMAP Ingredient", "High",
            "Concentrated source of fructans (high-FODMAP). One of the most common IBS triggers.")),
        new("onion", new Regex(@"\bonion\b", RegexOptions.Compiled), new("", "Onion", "High-FODMAP Ingredient", "High",
            "Contains fructans (high-FODMAP). Common trigger for bloating and gas in IBS patients.")),
        new("garlic", new Regex(@"\bgarlic\b", RegexOptions.Compiled), new("", "Garlic", "High-FODMAP Ingredient", "High",
            "Contains fructans (high-FODMAP). Common trigger for bloating and gas in IBS patients.")),
        new("wheat starch", null, new("", "Wheat Starch", "High-FODMAP Ingredient", "High",
            "Contains fructans. May trigger symptoms in fructan-sensitive individuals.")),
        new("wheat protein", null, new("", "Wheat Protein", "High-FODMAP Ingredient", "High",
            "Contains gluten and fructans. May trigger symptoms in sensitive individuals.")),
        new("wheat flour", null, new("", "Wheat Flour", "High-FODMAP Ingredient", "High",
            "Contains fructans. May trigger symptoms in fructan-sensitive individuals; gluten is a separate concern.")),
        new("wheat fiber", null, new("", "Wheat Fiber", "High-FODMAP Ingredient", "High",
            "Contains fructans. May trigger symptoms in fructan-sensitive individuals.")),
        new("wheat", new Regex(@"\bwheat\b", RegexOptions.Compiled), new("", "Wheat", "High-FODMAP Ingredient", "High",
            "Contains fructans. May trigger symptoms in fructan-sensitive individuals; gluten is a separate concern.")),

        // ── Prebiotic Fiber / FODMAP Triggers ──
        new("inulin", null, new("", "Inulin", "Prebiotic Fiber (FODMAP)", "High",
            "Fructan fiber — prebiotic but high-FODMAP. Can cause significant bloating and gas in IBS patients.")),
        new("chicory root", null, new("", "Chicory Root Fiber", "Prebiotic Fiber (FODMAP)", "High",
            "Rich source of inulin (fructan). Beneficial for microbiome but high-FODMAP — triggers bloating in sensitive individuals.")),
        new("fructooligosaccharide", null, new("", "FOS", "Prebiotic Fiber (FODMAP)", "High",
            "Fructan-type fiber — prebiotic but high-FODMAP. Common cause of gas and bloating.")),
        new("oligofructose", null, new("", "Oligofructose", "Prebiotic Fiber (FODMAP)", "High",
            "Short-chain fructan. High-FODMAP trigger for IBS symptoms.")),

        // ── Sweetener / Fructose Triggers ──
        new("high fructose corn syrup", null, new("", "High Fructose Corn Syrup", "Sweetener", SharedFodmapSeverities.GetRiskLevel("high fructose corn syrup")!,
            "Excess fructose can overwhelm absorption capacity, causing bloating, gas, and diarrhea — especially in fructose malabsorbers.")),
        new("agave", null, new("", "Agave Syrup", "Sweetener", SharedFodmapSeverities.GetRiskLevel("agave")!,
            "Very high in fructose (up to 90%). Can trigger symptoms in people with fructose malabsorption.")),

        // ── Dairy / Lactose Triggers ──
        new("whey powder", null, new("", "Whey Powder", "Dairy/Lactose", "Medium",
            "Concentrated source of lactose. Common trigger for lactose-intolerant individuals.")),
        new("whey", new Regex(@"\bwhey\b", RegexOptions.Compiled), new("", "Whey", "Dairy/Lactose", "Medium",
            "Contains lactose. May trigger bloating, gas, and diarrhea in lactose-intolerant individuals.")),
        new("skim milk powder", null, new("", "Skim Milk Powder", "Dairy/Lactose", "Medium",
            "Concentrated source of lactose. Common trigger for lactose-intolerant individuals.")),
        new("milk powder", null, new("", "Milk Powder", "Dairy/Lactose", SharedFodmapSeverities.GetRiskLevel("milk powder")!,
            "Concentrated source of lactose. Common trigger for lactose-intolerant individuals.")),
        new("milk solids", null, new("", "Milk Solids", "Dairy/Lactose", "Medium",
            "Contains lactose and milk proteins. Common trigger for lactose-intolerant individuals.")),
        new("cream powder", null, new("", "Cream Powder", "Dairy/Lactose", "Medium",
            "Contains lactose. May trigger symptoms in lactose-intolerant individuals.")),
        new("buttermilk", null, new("", "Buttermilk", "Dairy/Lactose", "Medium",
            "Contains lactose. May trigger GI symptoms in lactose-intolerant individuals.")),
        new("lactose", null, new("", "Lactose", "Dairy/Lactose", SharedFodmapSeverities.GetRiskLevel("lactose")!,
            "Milk sugar poorly digested by ~68% of the global population. Causes bloating, cramps, and diarrhea in lactose-intolerant individuals.")),
        new("skim milk", null, new("", "Skim Milk", "Dairy/Lactose", "Medium",
            "Contains lactose. May trigger GI symptoms in lactose-intolerant individuals.")),

        // ── Fruit Concentrate Fructose Triggers ──
        new("apple juice concentrate", null, new("", "Apple Juice Concentrate", "Fructose Source", "Medium",
            "Concentrated source of excess fructose. Can overwhelm fructose absorption and trigger bloating and diarrhea.")),
        new("pear juice concentrate", null, new("", "Pear Juice Concentrate", "Fructose Source", "Medium",
            "Concentrated source of excess fructose and sorbitol. Double FODMAP trigger for sensitive individuals.")),
        new("apple concentrate", null, new("", "Apple Concentrate", "Fructose Source", "Medium",
            "Concentrated source of excess fructose. Can trigger bloating and diarrhea in fructose malabsorbers.")),
        new("pear concentrate", null, new("", "Pear Concentrate", "Fructose Source", "Medium",
            "Concentrated source of excess fructose and sorbitol. Double FODMAP trigger for sensitive individuals.")),
        new("fruit juice concentrate", null, new("", "Fruit Juice Concentrate", "Fructose Source", "Medium",
            "Concentrated fructose source. May trigger symptoms in people with fructose malabsorption.")),
        new("fruit concentrate", null, new("", "Fruit Concentrate", "Fructose Source", "Medium",
            "Concentrated fructose source. May trigger symptoms in people with fructose malabsorption.")),

        // ── Additional Hydrocolloid Ingredient Patterns ──
        new("tragacanth", null, new("E413", "Tragacanth", "Thickener", "Low",
            "Natural gum; may cause bloating and gas in sensitive individuals.")),
        new("gum arabic", null, new("E414", "Gum Arabic", "Thickener", "Low",
            "Highly fermentable soluble fiber; may cause gas at high doses.")),
        new("sodium alginate", null, new("E401", "Sodium Alginate", "Thickener", "Low",
            "Seaweed-derived hydrocolloid; may cause gas and bloating in sensitive individuals.")),
        new("alginate", null, new("E401", "Sodium Alginate", "Thickener", "Low",
            "Seaweed-derived hydrocolloid; may cause gas and bloating in sensitive individuals.")),

        // ── GOS (Galacto-oligosaccharides) — Legumes & Soy ──
        new("chickpea flour", null, new("", "Chickpea Flour", "GOS Source", "High",
            "Concentrated source of galacto-oligosaccharides (GOS). High-FODMAP — triggers bloating and gas in IBS patients.")),
        new("chickpea", new Regex(@"\bchickpeas?\b", RegexOptions.Compiled), new("", "Chickpea", "GOS Source", "Medium",
            "Contains galacto-oligosaccharides (GOS). High-FODMAP trigger for bloating and gas.")),
        new("lentil", new Regex(@"\blentils?\b", RegexOptions.Compiled), new("", "Lentil", "GOS Source", "Medium",
            "Contains galacto-oligosaccharides (GOS). High-FODMAP trigger for bloating and gas.")),
        new("kidney bean", null, new("", "Kidney Bean", "GOS Source", "Medium",
            "Contains galacto-oligosaccharides (GOS). High-FODMAP trigger for bloating and gas.")),
        new("black bean", null, new("", "Black Bean", "GOS Source", "Medium",
            "Contains galacto-oligosaccharides (GOS). High-FODMAP trigger for bloating and gas.")),
        new("navy bean", null, new("", "Navy Bean", "GOS Source", "Medium",
            "Contains galacto-oligosaccharides (GOS). High-FODMAP trigger for bloating and gas.")),
        new("soy protein isolate", null, new("", "Soy Protein Isolate", "GOS Source", "High",
            "Concentrated soy source high in GOS. Dense FODMAP load per serving.")),
        new("soy flour", null, new("", "Soy Flour", "GOS Source", "High",
            "Concentrated soy source high in GOS. Dense FODMAP load per serving.")),
        new("textured vegetable protein", null, new("", "Textured Vegetable Protein", "GOS Source", "High",
            "Usually soy-derived, concentrated GOS source. Dense FODMAP load per serving.")),
        new("tvp", new Regex(@"\btvp\b", RegexOptions.Compiled), new("", "Textured Vegetable Protein", "GOS Source", "High",
            "Usually soy-derived, concentrated GOS source. Dense FODMAP load per serving.")),
        new("soybean", null, new("", "Soybean", "GOS Source", "Medium",
            "Contains galacto-oligosaccharides (GOS). May trigger bloating in GOS-sensitive individuals.")),

        // ── Polyols — Natural Sources (Fruits, Vegetables, Mushrooms) ──
        new("mushroom", new Regex(@"\bmushrooms?\b", RegexOptions.Compiled), new("", "Mushroom", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("mushroom")!,
            "Contains mannitol (polyol). High-FODMAP — common trigger for bloating and gas.")),
        new("prune", new Regex(@"\bprunes?\b", RegexOptions.Compiled), new("", "Prune", "Polyol Source", "High",
            "High in sorbitol (polyol). Concentrated FODMAP source — strongly associated with GI distress.")),
        new("plum", new Regex(@"\bplums?\b", RegexOptions.Compiled), new("", "Plum", "Polyol Source", "Medium",
            "Contains sorbitol (polyol). May trigger symptoms in polyol-sensitive individuals.")),
        new("cherry", new Regex(@"\bcherr(y|ies)\b", RegexOptions.Compiled), new("", "Cherry", "Polyol Source", "Medium",
            "Contains sorbitol (polyol). May trigger symptoms in polyol-sensitive individuals.")),
        new("apricot", new Regex(@"\bapricots?\b", RegexOptions.Compiled), new("", "Apricot", "Polyol Source", "Medium",
            "Contains sorbitol and polyols. May trigger symptoms in sensitive individuals.")),
        new("peach", new Regex(@"\bpeach(es)?\b", RegexOptions.Compiled), new("", "Peach", "Polyol Source", "Medium",
            "Contains sorbitol (polyol). May trigger symptoms in polyol-sensitive individuals.")),
        new("cauliflower", new Regex(@"\bcauliflowers?\b", RegexOptions.Compiled), new("", "Cauliflower", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("cauliflower")!,
            "Contains mannitol (polyol). May trigger symptoms in sensitive individuals at larger servings.")),
        new("avocado", new Regex(@"\bavocados?\b", RegexOptions.Compiled), new("", "Avocado", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("avocado")!,
            "Contains sorbitol (polyol). Dose-dependent — small amounts often tolerated.")),

        // ── Excess Fructose — Expanded ──
        new("honey", new Regex(@"\bhoney\b", RegexOptions.Compiled), new("", "Honey", "Fructose Source", SharedFodmapSeverities.GetRiskLevel("honey")!,
            "High in excess fructose. Can overwhelm absorption capacity and trigger bloating and diarrhea.")),
        new("mango", new Regex(@"\bmango\b", RegexOptions.Compiled), new("", "Mango", "Fructose Source", SharedFodmapSeverities.GetRiskLevel("mango")!,
            "Contains excess fructose. May trigger symptoms in fructose-sensitive individuals at higher servings.")),
        new("watermelon", new Regex(@"\bwatermelon\b", RegexOptions.Compiled), new("", "Watermelon", "Fructose Source", SharedFodmapSeverities.GetRiskLevel("watermelon")!,
            "Contains excess fructose and mannitol. Dual FODMAP trigger.")),
        new("apple juice", null, new("", "Apple Juice", "Fructose Source", "Medium",
            "High in excess fructose even without concentration. Common trigger for fructose malabsorbers.")),
        new("fruit juice", null, new("", "Fruit Juice", "Fructose Source", "Low",
            "May contain excess fructose depending on fruit type. Monitor for symptoms.")),

        // ── Fructans — Expanded ──
        new("onion salt", null, new("", "Onion Salt", "High-FODMAP Ingredient", "High",
            "Concentrated source of fructans (high-FODMAP). Common IBS trigger.")),
        new("garlic salt", null, new("", "Garlic Salt", "High-FODMAP Ingredient", "High",
            "Concentrated source of fructans (high-FODMAP). Common IBS trigger.")),
        new("shallot", new Regex(@"\bshallots?\b", RegexOptions.Compiled), new("", "Shallot", "High-FODMAP Ingredient", SharedFodmapSeverities.GetRiskLevel("shallot")!,
            "Contains fructans. Related to onion — common IBS trigger.")),
        new("leek", new Regex(@"\bleeks?\b", RegexOptions.Compiled), new("", "Leek", "High-FODMAP Ingredient", SharedFodmapSeverities.GetRiskLevel("leek")!,
            "Contains fructans. Common trigger for bloating and gas in IBS patients.")),
        new("wheat bran", null, new("", "Wheat Bran", "High-FODMAP Ingredient", "High",
            "Contains fructans. May trigger symptoms in fructan-sensitive individuals.")),

        // ── Dairy / Lactose — Expanded ──
        new("milk solids non-fat", null, new("", "Milk Solids Non-Fat", "Dairy/Lactose", "Medium",
            "Concentrated source of lactose. Common trigger for lactose-intolerant individuals.")),
        new("dry milk", null, new("", "Dry Milk", "Dairy/Lactose", "Medium",
            "Concentrated source of lactose. Common trigger for lactose-intolerant individuals.")),
        new("whey solids", null, new("", "Whey Solids", "Dairy/Lactose", "Medium",
            "Concentrated source of lactose. Common trigger for lactose-intolerant individuals.")),

        // ── Barley & Rye — Fructan Sources ──
        new("barley", new Regex(@"\bbarley\b", RegexOptions.Compiled), new("", "Barley", "High-FODMAP Ingredient", SharedFodmapSeverities.GetRiskLevel("barley")!,
            "Contains fructans. May trigger symptoms in fructan-sensitive individuals.")),
        new("rye", new Regex(@"\brye\b", RegexOptions.Compiled), new("", "Rye", "High-FODMAP Ingredient", SharedFodmapSeverities.GetRiskLevel("rye")!,
            "Contains fructans. May trigger symptoms in fructan-sensitive individuals.")),

        // ── Cashew & Pistachio — GOS Sources ──
        new("cashew", new Regex(@"\bcashews?\b", RegexOptions.Compiled), new("", "Cashew", "GOS Source", SharedFodmapSeverities.GetRiskLevel("cashew")!,
            "Contains galacto-oligosaccharides (GOS). High-FODMAP — common in snack and protein bars.")),
        new("pistachio", new Regex(@"\bpistachios?\b", RegexOptions.Compiled), new("", "Pistachio", "GOS Source", SharedFodmapSeverities.GetRiskLevel("pistachio")!,
            "Contains galacto-oligosaccharides (GOS). High-FODMAP — common in snack and protein bars.")),

        // ── Fructose Ingredient & Syrup Patterns ──
        new("crystalline fructose", null, new("", "Crystalline Fructose", "Fructose Source", "Medium",
            "Pure fructose. Can overwhelm absorption capacity and trigger bloating and diarrhea in fructose malabsorbers.")),
        new("maltitol syrup", null, new("", "Maltitol Syrup", "Sugar Alcohol", "High",
            "Liquid form of maltitol (polyol). High-FODMAP — causes severe bloating and diarrhea.")),
        new("sorbitol syrup", null, new("", "Sorbitol Syrup", "Sugar Alcohol", "High",
            "Liquid form of sorbitol (polyol). High-FODMAP — causes bloating, cramps, and osmotic diarrhea.")),
        new("fructose", new Regex(@"\bfructose\b", RegexOptions.Compiled), new("", "Fructose", "Fructose Source", "Low",
            "Excess fructose can overwhelm absorption capacity. May trigger symptoms in fructose malabsorbers.")),

        // ── Hidden Onion/Garlic — Low Confidence Flags ──
        new("natural flavors", null, new("", "Natural Flavors", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic; not always disclosed. Common hidden FODMAP source.")),
        new("natural flavour", null, new("", "Natural Flavours", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic; not always disclosed. Common hidden FODMAP source.")),
        new("natural flavouring", null, new("", "Natural Flavouring", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic; not always disclosed. Common hidden FODMAP source.")),
        new("vegetable powder", null, new("", "Vegetable Powder", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic; not always disclosed. Common hidden FODMAP source.")),
        new("seasoning", new Regex(@"\bseasoning\b", RegexOptions.Compiled), new("", "Seasoning", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic; not always disclosed. Common hidden FODMAP source.")),
        new("bouillon", new Regex(@"\bbouillon\b", RegexOptions.Compiled), new("", "Bouillon", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic; not always disclosed. Common hidden FODMAP source.")),
        new("stock", new Regex(@"\bstock\b", RegexOptions.Compiled), new("", "Stock", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic; not always disclosed. Common hidden FODMAP source.")),
        new("flavouring", new Regex(@"\bflavouring\b", RegexOptions.Compiled), new("", "Flavouring", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic; not always disclosed. Common hidden FODMAP source.")),
        new("spices", new Regex(@"\bspices\b", RegexOptions.Compiled), new("", "Spices", "Hidden FODMAP Risk", "Low",
            "May contain undisclosed onion/garlic powder. Common hidden FODMAP source.")),

        // ── Remaining FODMAP Gaps — Fructan Extracts ──
        new("onion extract", null, new("", "Onion Extract", "High-FODMAP Ingredient", "High",
            "Concentrated source of fructans (high-FODMAP). Common IBS trigger.")),
        new("garlic extract", null, new("", "Garlic Extract", "High-FODMAP Ingredient", "High",
            "Concentrated source of fructans (high-FODMAP). Common IBS trigger.")),
        new("garlic flavor", null, new("", "Garlic Flavor", "High-FODMAP Ingredient", "High",
            "Likely contains fructans. Common IBS trigger.")),
        new("onion flavor", null, new("", "Onion Flavor", "High-FODMAP Ingredient", "High",
            "Likely contains fructans. Common IBS trigger.")),
        new("garlic flavour", null, new("", "Garlic Flavour", "High-FODMAP Ingredient", "High",
            "Likely contains fructans. Common IBS trigger.")),
        new("onion flavour", null, new("", "Onion Flavour", "High-FODMAP Ingredient", "High",
            "Likely contains fructans. Common IBS trigger.")),

        // ── Remaining FODMAP Gaps — GOS ──
        new("hummus", new Regex(@"\bhummus\b", RegexOptions.Compiled), new("", "Hummus", "GOS Source", "Low",
            "Chickpea-based — contains galacto-oligosaccharides (GOS). High dose sensitivity.")),
        new("baked beans", null, new("", "Baked Beans", "GOS Source", "Medium",
            "Contains galacto-oligosaccharides (GOS). High-FODMAP trigger for bloating and gas.")),
        new("pea protein", null, new("", "Pea Protein", "GOS Source", "Low",
            "May contain residual GOS from peas. High dose sensitivity — concentrated forms increase risk.")),

        // ── Remaining FODMAP Gaps — Excess Fructose (Whole Fruit) ──
        new("pear", new Regex(@"\bpear\b", RegexOptions.Compiled), new("", "Pear", "Fructose Source", "Low",
            "Contains excess fructose and sorbitol. Dual FODMAP trigger in sensitive individuals.")),
        new("apple", new Regex(@"\bapple\b", RegexOptions.Compiled), new("", "Apple", "Fructose Source", "Low",
            "Contains excess fructose. May trigger symptoms in fructose-sensitive individuals.")),
        new("fruit puree", null, new("", "Fruit Puree", "Fructose Source", "Low",
            "Concentrated fructose source. May trigger symptoms in fructose malabsorbers.")),
        new("fruit paste", null, new("", "Fruit Paste", "Fructose Source", "Low",
            "Concentrated fructose source. May trigger symptoms in fructose malabsorbers.")),
        new("date paste", null, new("", "Date Paste", "Fructose Source", "Medium",
            "Concentrated fructose source. Dates are high in excess fructose.")),

        // ── Remaining FODMAP Gaps — Dairy (Casein) ──
        new("whey concentrate", null, new("", "Whey Concentrate", "Dairy/Lactose", "Medium",
            "Contains lactose. May trigger symptoms in lactose-intolerant individuals.")),
        new("caseinate", null, new("", "Caseinate", "Dairy/Lactose", "Low",
            "Dairy protein derivative. Low in lactose but may trigger symptoms in dairy-protein-sensitive individuals.")),
        new("casein", new Regex(@"\bcasein\b", RegexOptions.Compiled), new("", "Casein", "Dairy/Lactose", "Low",
            "Dairy protein — low in lactose but may trigger symptoms in dairy-protein-sensitive individuals.")),

        // ── Non-FODMAP IBS Triggers — Stimulant/Motility ──
        new("caffeine", new Regex(@"\bcaffeine\b", RegexOptions.Compiled), new("", "Caffeine", "Stimulant/Motility", "Low",
            "Stimulates gut motility and increases gastric acid. May worsen diarrhea-predominant IBS.")),
        new("coffee", new Regex(@"\bcoffee\b", RegexOptions.Compiled), new("", "Coffee", "Stimulant/Motility", "Low",
            "Stimulates gut motility and increases gastric acid. May worsen diarrhea-predominant IBS.")),
        new("guarana", new Regex(@"\bguarana\b", RegexOptions.Compiled), new("", "Guarana", "Stimulant/Motility", "Medium",
            "Natural caffeine source. Stimulates gut motility — may worsen IBS symptoms.")),
        new("green tea extract", null, new("", "Green Tea Extract", "Stimulant/Motility", "Low",
            "Contains caffeine. May stimulate gut motility in sensitive individuals.")),

        // ── Non-FODMAP IBS Triggers — Spicy/Irritant ──
        new("chilli", new Regex(@"\bchillis?\b", RegexOptions.Compiled), new("", "Chilli", "Spicy/Irritant", "Low",
            "Contains capsaicin which can irritate the gut lining and accelerate transit. Common IBS trigger.")),
        new("chili", new Regex(@"\bchilis?\b", RegexOptions.Compiled), new("", "Chili", "Spicy/Irritant", "Low",
            "Contains capsaicin which can irritate the gut lining and accelerate transit. Common IBS trigger.")),
        new("capsicum", new Regex(@"\bcapsicum\b", RegexOptions.Compiled), new("", "Capsicum", "Spicy/Irritant", "Low",
            "Contains capsaicin. May irritate the gut lining in sensitive individuals.")),
        new("cayenne", new Regex(@"\bcayenne\b", RegexOptions.Compiled), new("", "Cayenne", "Spicy/Irritant", "Medium",
            "High capsaicin content. Can irritate gut lining and accelerate transit — common IBS trigger.")),
        new("hot pepper", null, new("", "Hot Pepper", "Spicy/Irritant", "Low",
            "Contains capsaicin which can irritate the gut lining and accelerate transit.")),

        // ── Alcohol & Fermented ──
        new("beer", null, new("", "Beer", "Alcohol & Fermented", "Medium",
            "Beer contains gluten, alcohol, and fermentable carbohydrates that can irritate the gut.")),
        new("wine", new Regex(@"\bwine\b", RegexOptions.Compiled), new("", "Wine", "Alcohol & Fermented", "Low",
            "Wine in moderate amounts may be tolerated. High-histamine wines may trigger symptoms in sensitive individuals.")),
        new("cider", null, new("", "Cider", "Alcohol & Fermented", "Medium",
            "Cider contains alcohol and excess fructose from apples.")),
        new("kombucha", null, new("", "Kombucha", "Alcohol & Fermented", "Low",
            "Kombucha contains probiotics that may benefit gut health, but carbonation and residual sugars may cause discomfort.")),
        new("kefir", null, new("", "Kefir", "Alcohol & Fermented", "Low",
            "Kefir is a probiotic-rich fermented dairy that may actually support gut health for many people.")),

        // ── Emulsifier Names on Labels ──
        new("mono and diglycerides", null, new("E471", "Mono and Diglycerides", "Emulsifier", "Medium",
            "Common emulsifier that may affect gut barrier integrity at high intake levels.")),
        new("datem", new Regex(@"\bdatem\b", RegexOptions.Compiled), new("E472E", "DATEM", "Emulsifier", "Medium",
            "Diacetyl tartaric acid ester — may affect gut microbiome composition.")),
        new("pgpr", new Regex(@"\bpgpr\b", RegexOptions.Compiled), new("E476", "PGPR", "Emulsifier", "Low",
            "Polyglycerol polyricinoleate — common in chocolate.")),
        new("sorbitan monostearate", null, new("E491", "Sorbitan Monostearate", "Emulsifier", "Low",
            "Sorbitan ester emulsifier. May affect gut barrier.")),
        new("sodium stearoyl lactylate", null, new("E481", "Sodium Stearoyl Lactylate", "Emulsifier", "Low",
            "Bread emulsifier. May affect gut barrier at high intake.")),
        new("calcium stearoyl lactylate", null, new("E482", "Calcium Stearoyl Lactylate", "Emulsifier", "Low",
            "Bread emulsifier. May affect gut barrier at high intake.")),

        // ── Preservative Names on Labels ──
        new("potassium sorbate", null, new("E202", "Potassium Sorbate", "Preservative", "Low",
            "Antimicrobial preservative that may modestly affect gut flora.")),
        new("sulfite", new Regex(@"\bsulfites?\b", RegexOptions.Compiled), new("E220", "Sulfites", "Preservative/Sulfite", "Medium",
            "Sulfites can trigger GI symptoms in sulfite-sensitive individuals.")),
        new("sulphite", new Regex(@"\bsulphites?\b", RegexOptions.Compiled), new("E220", "Sulphites", "Preservative/Sulfite", "Medium",
            "Sulphites can trigger GI symptoms in sensitive individuals.")),
        new("sodium nitrate", null, new("E251", "Sodium Nitrate", "Preservative", "Medium",
            "Converts to nitrite in the body. Similar gut concerns as sodium nitrite.")),
        new("potassium nitrate", null, new("E252", "Potassium Nitrate", "Preservative", "Medium",
            "Converts to nitrite. Similar gut inflammation concerns.")),
        new("nitrate", new Regex(@"\bnitrates?\b", RegexOptions.Compiled), new("E252", "Nitrate", "Preservative", "Medium",
            "Nitrates convert to nitrites. Associated with intestinal inflammation.")),
        new("nitrite", new Regex(@"\bnitrites?\b", RegexOptions.Compiled), new("E250", "Nitrite", "Preservative", "Medium",
            "Associated with intestinal inflammation and nitrosamine formation.")),

        // ── Sweetener Names on Labels ──
        new("stevia", null, new("E960", "Stevia", "Sweetener", "Low",
            "Natural sweetener. Generally well-tolerated but some individuals report bloating.")),
        new("monk fruit", null, new("", "Monk Fruit Extract", "Sweetener", "Low",
            "Natural sweetener. Generally well-tolerated.")),
        new("allulose", null, new("", "Allulose", "Sweetener", "Low",
            "Rare sugar. Better absorbed than sugar alcohols but may cause GI symptoms at high doses.")),
        new("neotame", null, new("E961", "Neotame", "Artificial Sweetener", "Medium",
            "Potent artificial sweetener. Limited data on gut effects.")),
        new("advantame", null, new("E969", "Advantame", "Artificial Sweetener", "Medium",
            "Ultra-potent artificial sweetener. Limited human data on gut microbiome effects.")),
        new("cyclamate", null, new("E952", "Cyclamate", "Artificial Sweetener", "Medium",
            "Artificial sweetener. Some evidence of gut microbiome disruption.")),

        // ── Modified Starch Names on Labels ──
        new("modified starch", null, new("E1442", "Modified Starch", "Thickener", "Low",
            "Modified food starch. May resist digestion and cause gas via colonic fermentation.")),
        new("modified food starch", null, new("E1442", "Modified Food Starch", "Thickener", "Low",
            "Modified food starch. May resist digestion and cause gas.")),
        new("modified corn starch", null, new("E1442", "Modified Corn Starch", "Thickener", "Low",
            "Modified food starch. May resist digestion and cause gas.")),
        new("modified tapioca starch", null, new("E1442", "Modified Tapioca Starch", "Thickener", "Low",
            "Modified food starch. May resist digestion and cause gas.")),

        // ── Colorant Names on Labels ──
        new("tartrazine", null, new("E102", "Tartrazine", "Artificial Colorant", "Low",
            "Azo dye that may increase intestinal permeability.")),
        new("sunset yellow", null, new("E110", "Sunset Yellow", "Artificial Colorant", "Low",
            "Azo dye associated with increased intestinal permeability.")),
        new("yellow 5", null, new("E102", "Yellow 5 / Tartrazine", "Artificial Colorant", "Low",
            "Azo dye. May increase intestinal permeability.")),
        new("yellow 6", null, new("E110", "Yellow 6 / Sunset Yellow", "Artificial Colorant", "Low",
            "Azo dye. May increase intestinal permeability.")),
        new("red 3", null, new("E127", "Red 3 / Erythrosine", "Artificial Colorant", "Low",
            "May affect gut microbiome at high doses.")),
        new("blue 1", null, new("E133", "Blue 1 / Brilliant Blue", "Artificial Colorant", "Low",
            "May increase intestinal permeability at high doses.")),
        new("caramel color", null, new("E150D", "Caramel Color", "Colorant", "Low",
            "Most common caramel coloring. Contains 4-MEI.")),
        new("caramel colour", null, new("E150D", "Caramel Colour", "Colorant", "Low",
            "Most common caramel coloring. Contains 4-MEI.")),
        new("annatto", null, new("E160B", "Annatto", "Colorant", "Low",
            "Natural colorant. May trigger symptoms in a small subset of sensitive individuals.")),

        // ── FODMAP Ingredient Patterns ──
        new("wheat germ", null, new("", "Wheat Germ", "High-FODMAP Ingredient", "High",
            "Contains fructans. May trigger symptoms in fructan-sensitive individuals.")),
        new("wheat dextrin", null, new("", "Wheat Dextrin", "Prebiotic Fiber (FODMAP)", "Medium",
            "Wheat-derived soluble fiber — may contain residual fructans.")),
        new("durum wheat", null, new("", "Durum Wheat", "High-FODMAP Ingredient", "High",
            "Durum wheat is high in fructans.")),
        new("triticale", null, new("", "Triticale", "High-FODMAP Ingredient", "High",
            "Wheat-rye hybrid — high in fructans.")),
        new("corn syrup", null, new("", "Corn Syrup", "Fructose Source", "Low",
            "Regular corn syrup is mostly glucose. HFCS variants contain excess fructose.")),
        new("invert sugar", null, new("", "Invert Sugar", "Fructose Source", "Medium",
            "Invert sugar contains free fructose — moderate FODMAP concern.")),
        new("fruit puree", null, new("", "Fruit Puree", "Fructose Source", "Low",
            "Concentrated fructose source depending on fruit type.")),

        // ── Dairy Patterns ──
        new("milk protein concentrate", null, new("", "Milk Protein Concentrate", "Dairy/Lactose", "Medium",
            "Retains moderate lactose. Common trigger for lactose-intolerant individuals.")),
        new("whey permeate", null, new("", "Whey Permeate", "Dairy/Lactose", "High",
            "Concentrated lactose — very high FODMAP trigger.")),
        new("milk fat", null, new("", "Milk Fat", "Dairy/Lactose", "Low",
            "Milk fat/butter fat has minimal lactose.")),
        new("butter oil", null, new("", "Butter Oil", "Dairy/Lactose", "Low",
            "Butter oil has minimal lactose. May trigger dairy-protein sensitivity.")),
        new("nonfat dry milk", null, new("", "Nonfat Dry Milk", "Dairy/Lactose", "Medium",
            "Concentrated source of lactose.")),

        // ── GOS Patterns ──
        new("bean flour", null, new("", "Bean Flour", "GOS Source", "High",
            "Concentrated legume — high in GOS.")),
        new("lentil flour", null, new("", "Lentil Flour", "GOS Source", "High",
            "Lentil flour retains high GOS.")),
        new("chickpea protein", null, new("", "Chickpea Protein", "GOS Source", "Medium",
            "May retain moderate GOS from chickpea processing.")),
        new("faba bean", null, new("", "Faba Bean", "GOS Source", "High",
            "Faba beans are high in GOS.")),

        // ── Hidden FODMAP Risks ──
        new("dehydrated vegetables", null, new("", "Dehydrated Vegetables", "Hidden FODMAP Risk", "Low",
            "Dehydrated vegetable blends often contain onion and garlic.")),
        new("vegetable extract", null, new("", "Vegetable Extract", "Hidden FODMAP Risk", "Low",
            "May contain concentrated onion/garlic — common hidden FODMAP source.")),
        new("savory flavoring", null, new("", "Savory Flavoring", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic derivatives.")),
        new("savoury flavouring", null, new("", "Savoury Flavouring", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic derivatives.")),
        new("yeast extract", null, new("", "Yeast Extract", "Hidden FODMAP Risk", "Low",
            "Some yeast extracts contain trace onion/garlic. Also high in glutamate.")),

        // ── Composed Meals & Dishes ──
        new("pizza", null, new("", "Pizza", "High-FODMAP Ingredient", "Medium",
            "Pizza contains wheat crust (fructans) and often garlic/onion in sauce.")),
        new("lasagna", null, new("", "Lasagna", "High-FODMAP Ingredient", "Medium",
            "Lasagna contains wheat pasta sheets and typically onion/garlic in sauce.")),
        new("burrito", null, new("", "Burrito", "High-FODMAP Ingredient", "Medium",
            "Wheat tortilla with beans — contains fructans and GOS.")),
        new("ramen", null, new("", "Ramen", "High-FODMAP Ingredient", "Medium",
            "Wheat noodles (fructans) with broth often containing onion and garlic.")),
        new("pad thai", null, new("", "Pad Thai", "High-FODMAP Ingredient", "Low",
            "Rice noodle dish — generally lower FODMAP unless garlic/shallot heavy.")),
        new("sushi", null, new("", "Sushi", "High-FODMAP Ingredient", "Low",
            "Rice and fish is generally low FODMAP. Soy sauce adds minimal risk.")),
        new("curry", null, new("", "Curry", "High-FODMAP Ingredient", "Medium",
            "Most curries contain onion and garlic — common FODMAP triggers.")),
        new("stir fry", null, new("", "Stir Fry", "High-FODMAP Ingredient", "Medium",
            "Stir fries typically contain garlic and onion.")),
        new("fried rice", null, new("", "Fried Rice", "High-FODMAP Ingredient", "Medium",
            "Usually contains onion and garlic.")),
        new("spaghetti", null, new("", "Spaghetti", "High-FODMAP Ingredient", "Medium",
            "Wheat pasta (fructans) — sauce typically contains garlic and onion.")),
        new("pasta", null, new("", "Pasta", "High-FODMAP Ingredient", "Medium",
            "Wheat-based pasta contains fructans. Gluten-free alternatives are lower FODMAP.")),
        new("noodle", null, new("", "Noodle", "High-FODMAP Ingredient", "Medium",
            "Wheat noodles contain fructans. Rice noodles are lower FODMAP.")),
        new("udon", null, new("", "Udon", "High-FODMAP Ingredient", "Medium",
            "Thick wheat noodles — contains fructans.")),
        new("sourdough", null, new("", "Sourdough", "High-FODMAP Ingredient", "Low",
            "Sourdough fermentation reduces fructan content compared to regular bread.")),
        new("naan", null, new("", "Naan", "High-FODMAP Ingredient", "Medium",
            "Wheat flatbread with garlic often added.")),
        new("pita", null, new("", "Pita", "High-FODMAP Ingredient", "Medium",
            "Wheat-based flatbread — contains fructans.")),
        new("ciabatta", null, new("", "Ciabatta", "High-FODMAP Ingredient", "Medium",
            "Italian wheat bread — contains fructans.")),
        new("croissant", null, new("", "Croissant", "High-FODMAP Ingredient", "Medium",
            "Wheat and butter pastry — fructans and lactose.")),
        new("bagel", null, new("", "Bagel", "High-FODMAP Ingredient", "Medium",
            "Wheat-based — contains fructans.")),
        new("wrap", null, new("", "Wrap", "High-FODMAP Ingredient", "Medium",
            "Usually wheat-based wrap — contains fructans.")),
        new("sandwich", null, new("", "Sandwich", "High-FODMAP Ingredient", "Medium",
            "Bread-based — wheat fructans plus fillings may add FODMAP load.")),
        new("taco", null, new("", "Taco", "High-FODMAP Ingredient", "Low",
            "Corn taco shell is low FODMAP but fillings may contain onion/beans.")),
        new("quesadilla", null, new("", "Quesadilla", "High-FODMAP Ingredient", "Medium",
            "Wheat tortilla with cheese — fructans and lactose.")),
        new("risotto", null, new("", "Risotto", "High-FODMAP Ingredient", "Medium",
            "Rice dish but typically contains onion and garlic.")),
        new("dumpling", null, new("", "Dumpling", "High-FODMAP Ingredient", "Medium",
            "Wheat wrapper with fillings often containing garlic and onion.")),
        new("gyoza", null, new("", "Gyoza", "High-FODMAP Ingredient", "Medium",
            "Japanese dumplings — wheat wrapper, garlic and cabbage filling.")),
        new("wonton", null, new("", "Wonton", "High-FODMAP Ingredient", "Medium",
            "Wheat wrappers with fillings often containing garlic/onion.")),
        new("samosa", null, new("", "Samosa", "High-FODMAP Ingredient", "Medium",
            "Wheat pastry stuffed with potato and onion.")),
        new("empanada", null, new("", "Empanada", "High-FODMAP Ingredient", "Medium",
            "Wheat pastry with onion-containing filling.")),
        new("biryani", null, new("", "Biryani", "High-FODMAP Ingredient", "Medium",
            "Spiced rice with onion and garlic.")),

        // ── Dried Fruits ──
        new("dried mango", null, new("", "Dried Mango", "Fructose Source", "Medium",
            "Concentrated fructose from dehydration.")),
        new("dried apricot", null, new("", "Dried Apricot", "Polyol Source", "Medium",
            "Concentrated sorbitol from dehydration.")),
        new("dried fig", null, new("", "Dried Fig", "Fructose Source", "Medium",
            "Concentrated fructose from dehydration.")),
        new("date", null, new("", "Dates", "Fructose Source", "Medium",
            "Dates contain moderate excess fructose — higher when dried.")),
        new("trail mix", null, new("", "Trail Mix", "Polyol Source", "Medium",
            "Often contains dried stone fruits and cashews/pistachios — mixed FODMAP triggers.")),
        new("raisin", null, new("", "Raisins", "Fructose Source", "Low",
            "Raisins contain moderate fructose — generally tolerated in small amounts.")),

        // ── Condiments & Sauces ──
        new("soy sauce", null, new("", "Soy Sauce", "High-FODMAP Ingredient", "Low",
            "Small amounts of wheat in fermentation — generally low FODMAP in typical servings.")),
        new("bbq sauce", null, new("", "BBQ Sauce", "Fructose Source", "Medium",
            "Often contains HFCS, onion, and garlic.")),
        new("tomato sauce", null, new("", "Tomato Sauce", "High-FODMAP Ingredient", "Low",
            "Plain tomato sauce is low FODMAP but commercial versions often add onion/garlic.")),
        new("ketchup", null, new("", "Ketchup", "Fructose Source", "Low",
            "Contains moderate sugar/HFCS but typically used in small amounts.")),
        new("mayonnaise", null, new("", "Mayonnaise", "High-FODMAP Ingredient", "Low",
            "Plain mayo is generally low FODMAP — egg, oil, and vinegar base.")),
        new("mustard", null, new("", "Mustard", "High-FODMAP Ingredient", "Low",
            "Plain mustard is generally low FODMAP in typical serving sizes.")),
        new("pesto", null, new("", "Pesto", "High-FODMAP Ingredient", "Medium",
            "Traditional pesto contains garlic. Pine nut base is low FODMAP.")),
        new("salsa", null, new("", "Salsa", "High-FODMAP Ingredient", "Medium",
            "Often contains onion and garlic.")),
        new("hoisin sauce", null, new("", "Hoisin Sauce", "High-FODMAP Ingredient", "Medium",
            "Contains garlic and sometimes wheat.")),
        new("teriyaki sauce", null, new("", "Teriyaki Sauce", "High-FODMAP Ingredient", "Medium",
            "Contains soy sauce (wheat) and often garlic/onion.")),
    ];

    internal static readonly IReadOnlyList<IngredientRiskEntry> WholeFoodRiskPatterns =
    [
        // ── Fructan Sources ──
        new("garlic", null, new("", "Garlic", "High-FODMAP Ingredient", "High",
            "Garlic is very high in fructans — one of the most common FODMAP triggers.")),
        new("onion", null, new("", "Onion", "High-FODMAP Ingredient", "High",
            "Onion is very high in fructans — one of the most common IBS triggers.")),
        new("shallot", null, new("", "Shallot", "High-FODMAP Ingredient", SharedFodmapSeverities.GetRiskLevel("shallot")!,
            "Shallots contain fructans. Related to onion — common IBS trigger.")),
        new("leek", null, new("", "Leek", "High-FODMAP Ingredient", "Medium",
            "Leeks contain fructans. Common trigger for bloating and gas.")),
        new("kimchi", null, new("", "Kimchi", "High-FODMAP Ingredient", "Medium",
            "Kimchi contains garlic and onion — both high in fructans.")),
        new("bread", null, new("", "Bread", "High-FODMAP Ingredient", "Medium",
            "Most bread is wheat-based and contains fructans.")),
        new("asparagus", null, new("", "Asparagus", "High-FODMAP Ingredient", "Medium",
            "Contains moderate fructans.")),
        new("artichoke", null, new("", "Artichoke", "High-FODMAP Ingredient", "High",
            "Very high in fructans and inulin-type fructans.")),
        new("brussels sprout", null, new("", "Brussels Sprouts", "High-FODMAP Ingredient", "Medium",
            "Contains moderate fructans.")),
        new("beetroot", null, new("", "Beetroot", "High-FODMAP Ingredient", "Medium",
            "Contains moderate fructans and GOS.")),
        new("wheat", new Regex(@"\bwheat\b", RegexOptions.Compiled | RegexOptions.IgnoreCase), new("", "Wheat", "High-FODMAP Ingredient", "High",
            "Contains fructans. One of the most common FODMAP triggers.")),
        new("rye", new Regex(@"\brye\b", RegexOptions.Compiled | RegexOptions.IgnoreCase), new("", "Rye", "High-FODMAP Ingredient", "High",
            "Contains significant fructans.")),
        new("barley", new Regex(@"\bbarley\b", RegexOptions.Compiled | RegexOptions.IgnoreCase), new("", "Barley", "High-FODMAP Ingredient", "High",
            "Contains significant fructans.")),

        // ── GOS Sources ──
        new("lentil", null, new("", "Lentils", "GOS Source", SharedFodmapSeverities.GetRiskLevel("lentil")!,
            "Lentils are high in galacto-oligosaccharides (GOS). Common cause of bloating and gas.")),
        new("chickpea", null, new("", "Chickpeas", "GOS Source", SharedFodmapSeverities.GetRiskLevel("chickpea")!,
            "Chickpeas are high in GOS. Common cause of bloating and gas.")),
        new("black bean", null, new("", "Black Beans", "GOS Source", SharedFodmapSeverities.GetRiskLevel("black bean")!,
            "Black beans are high in GOS. Common trigger for gas and bloating.")),
        new("kidney bean", null, new("", "Kidney Beans", "GOS Source", SharedFodmapSeverities.GetRiskLevel("kidney bean")!,
            "Kidney beans are high in GOS. Common trigger for gas and bloating.")),
        new("soybean", null, new("", "Soybean", "GOS Source", SharedFodmapSeverities.GetRiskLevel("soybean")!,
            "Contains high GOS.")),
        new("baked bean", null, new("", "Baked Beans", "GOS Source", SharedFodmapSeverities.GetRiskLevel("baked bean")!,
            "Navy/haricot beans with high GOS.")),
        new("navy bean", null, new("", "Navy Bean", "GOS Source", SharedFodmapSeverities.GetRiskLevel("navy bean")!,
            "High in GOS.")),
        new("pinto bean", null, new("", "Pinto Bean", "GOS Source", SharedFodmapSeverities.GetRiskLevel("pinto bean")!,
            "High in GOS.")),
        new("split pea", null, new("", "Split Pea", "GOS Source", SharedFodmapSeverities.GetRiskLevel("split pea")!,
            "High in GOS.")),
        new("hummus", null, new("", "Hummus", "GOS Source", "Medium",
            "Chickpea-based — contains GOS and garlic fructans.")),
        new("falafel", null, new("", "Falafel", "GOS Source", "High",
            "Chickpea-based with garlic and onion.")),
        new("edamame", null, new("", "Edamame", "GOS Source", "Medium",
            "Young soybeans — moderate GOS.")),

        // ── Fructose Sources ──
        new("honey", null, new("", "Honey", "Fructose Source", SharedFodmapSeverities.GetRiskLevel("honey")!,
            "Honey is high in excess fructose. Can overwhelm absorption capacity.")),
        new("watermelon", null, new("", "Watermelon", "Fructose Source", SharedFodmapSeverities.GetRiskLevel("watermelon")!,
            "Watermelon contains excess fructose and mannitol. Dual FODMAP trigger.")),
        new("mango", null, new("", "Mango", "Fructose Source", SharedFodmapSeverities.GetRiskLevel("mango")!,
            "Mango contains excess fructose. May trigger symptoms in fructose-sensitive individuals at higher servings.")),
        new("fig", null, new("", "Fig", "Fructose Source", "Medium",
            "Figs contain moderate excess fructose. Dried figs are higher.")),
        new("grape", null, new("", "Grape", "Fructose Source", "Low",
            "Grapes contain moderate fructose in large quantities.")),

        // ── Polyol Sources ──
        new("mushroom", null, new("", "Mushroom", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("mushroom")!,
            "Most mushrooms are high in mannitol (polyol). Common FODMAP trigger.")),
        new("cauliflower", null, new("", "Cauliflower", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("cauliflower")!,
            "Cauliflower contains significant mannitol (polyol).")),
        new("cherry", new Regex(@"\bcherr(y|ies)\b", RegexOptions.Compiled | RegexOptions.IgnoreCase), new("", "Cherry", "Polyol Source", "Medium",
            "Cherries contain sorbitol and excess fructose. Dual FODMAP trigger.")),
        new("blackberry", new Regex(@"\bblackberr(y|ies)\b", RegexOptions.Compiled | RegexOptions.IgnoreCase), new("", "Blackberry", "Polyol Source", "Low",
            "Blackberries contain moderate polyols.")),
        new("avocado", null, new("", "Avocado", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("avocado")!,
            "Avocado contains sorbitol. Dose-dependent — small amounts often tolerated.")),
        new("apple", MatchUtils.WordBoundary("apple"), new("", "Apple", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("apple")!,
            "Apples contain both excess fructose and sorbitol — double FODMAP load.")),
        new("pear", MatchUtils.WordBoundary("pear"), new("", "Pear", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("pear")!,
            "Pears have very high excess fructose and sorbitol.")),
        new("peach", null, new("", "Peach", "Polyol Source", "Low",
            "Peaches contain moderate sorbitol.")),
        new("apricot", null, new("", "Apricot", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("apricot")!,
            "Contains moderate sorbitol.")),
        new("plum", null, new("", "Plum", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("plum")!,
            "Contains moderate sorbitol.")),
        new("prune", null, new("", "Prune", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("prune")!,
            "Dried plums — concentrated sorbitol.")),
        new("nectarine", null, new("", "Nectarine", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("nectarine")!,
            "Contains moderate sorbitol.")),
        new("lychee", null, new("", "Lychee", "Polyol Source", "Medium",
            "Contains moderate sorbitol.")),
        new("sweet potato", null, new("", "Sweet Potato", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("sweet potato")!,
            "Contains moderate mannitol.")),
        new("celery", null, new("", "Celery", "Polyol Source", SharedFodmapSeverities.GetRiskLevel("celery")!,
            "Contains moderate mannitol.")),

        // ── Dairy/Lactose ──
        new("milk", new Regex(@"\bmilk\b(?! thistle)", RegexOptions.Compiled | RegexOptions.IgnoreCase), new("", "Milk", "Dairy/Lactose", SharedFodmapSeverities.GetRiskLevel("milk")!,
            "Milk contains lactose — trigger for lactose-intolerant individuals.")),
        new("yogurt", new Regex(@"\byogu?h?rt\b", RegexOptions.Compiled | RegexOptions.IgnoreCase), new("", "Yogurt", "Dairy/Lactose", SharedFodmapSeverities.GetRiskLevel("yogurt")!,
            "Contains moderate lactose.")),
        new("ice cream", null, new("", "Ice Cream", "Dairy/Lactose", SharedFodmapSeverities.GetRiskLevel("ice cream")!,
            "High in lactose from milk and cream.")),
        new("cream", new Regex(@"\bcream\b(?! of tartar)", RegexOptions.Compiled | RegexOptions.IgnoreCase), new("", "Cream", "Dairy/Lactose", SharedFodmapSeverities.GetRiskLevel("cream")!,
            "Contains moderate lactose.")),
        new("cheese", new Regex(@"\bcheese\b", RegexOptions.Compiled | RegexOptions.IgnoreCase), new("", "Cheese", "Dairy/Lactose", "Low",
            "Aged cheeses are low lactose. Fresh cheeses (ricotta, cottage) are higher.")),

        // ── GOS Patterns ──
        new("bean flour", null, new("", "Bean Flour", "GOS Source", "High",
            "Concentrated legume — high in GOS.")),
        new("lentil flour", null, new("", "Lentil Flour", "GOS Source", "High",
            "Lentil flour retains high GOS.")),
        new("chickpea protein", null, new("", "Chickpea Protein", "GOS Source", "Medium",
            "May retain moderate GOS from chickpea processing.")),
        new("faba bean", null, new("", "Faba Bean", "GOS Source", "High",
            "Faba beans are high in GOS.")),

        // ── Hidden FODMAP Risks ──
        new("dehydrated vegetables", null, new("", "Dehydrated Vegetables", "Hidden FODMAP Risk", "Low",
            "Dehydrated vegetable blends often contain onion and garlic.")),
        new("vegetable extract", null, new("", "Vegetable Extract", "Hidden FODMAP Risk", "Low",
            "May contain concentrated onion/garlic — common hidden FODMAP source.")),
        new("savory flavoring", null, new("", "Savory Flavoring", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic derivatives.")),
        new("savoury flavouring", null, new("", "Savoury Flavouring", "Hidden FODMAP Risk", "Low",
            "Often contains onion/garlic derivatives.")),
        new("yeast extract", null, new("", "Yeast Extract", "Hidden FODMAP Risk", "Low",
            "Some yeast extracts contain trace onion/garlic. Also high in glutamate.")),

        // ── Composed Meals & Dishes ──
        new("pizza", null, new("", "Pizza", "High-FODMAP Ingredient", "Medium",
            "Pizza contains wheat crust (fructans) and often garlic/onion in sauce.")),
        new("lasagna", null, new("", "Lasagna", "High-FODMAP Ingredient", "Medium",
            "Lasagna contains wheat pasta sheets and typically onion/garlic in sauce.")),
        new("burrito", null, new("", "Burrito", "High-FODMAP Ingredient", "Medium",
            "Wheat tortilla with beans — contains fructans and GOS.")),
        new("ramen", null, new("", "Ramen", "High-FODMAP Ingredient", "Medium",
            "Wheat noodles (fructans) with broth often containing onion and garlic.")),
        new("pad thai", null, new("", "Pad Thai", "High-FODMAP Ingredient", "Low",
            "Rice noodle dish — generally lower FODMAP unless garlic/shallot heavy.")),
        new("sushi", null, new("", "Sushi", "High-FODMAP Ingredient", "Low",
            "Rice and fish is generally low FODMAP. Soy sauce adds minimal risk.")),
        new("curry", null, new("", "Curry", "High-FODMAP Ingredient", "Medium",
            "Most curries contain onion and garlic — common FODMAP triggers.")),
        new("stir fry", null, new("", "Stir Fry", "High-FODMAP Ingredient", "Medium",
            "Stir fries typically contain garlic and onion.")),
        new("fried rice", null, new("", "Fried Rice", "High-FODMAP Ingredient", "Medium",
            "Usually contains onion and garlic.")),
        new("spaghetti", null, new("", "Spaghetti", "High-FODMAP Ingredient", "Medium",
            "Wheat pasta (fructans) — sauce typically contains garlic and onion.")),
        new("pasta", null, new("", "Pasta", "High-FODMAP Ingredient", "Medium",
            "Wheat-based pasta contains fructans. Gluten-free alternatives are lower FODMAP.")),
        new("noodle", null, new("", "Noodle", "High-FODMAP Ingredient", "Medium",
            "Wheat noodles contain fructans. Rice noodles are lower FODMAP.")),
        new("udon", null, new("", "Udon", "High-FODMAP Ingredient", "Medium",
            "Thick wheat noodles — contains fructans.")),
        new("sourdough", null, new("", "Sourdough", "High-FODMAP Ingredient", "Low",
            "Sourdough fermentation reduces fructan content compared to regular bread.")),
        new("naan", null, new("", "Naan", "High-FODMAP Ingredient", "Medium",
            "Wheat flatbread with garlic often added.")),
        new("pita", null, new("", "Pita", "High-FODMAP Ingredient", "Medium",
            "Wheat-based flatbread — contains fructans.")),
        new("ciabatta", null, new("", "Ciabatta", "High-FODMAP Ingredient", "Medium",
            "Italian wheat bread — contains fructans.")),
        new("croissant", null, new("", "Croissant", "High-FODMAP Ingredient", "Medium",
            "Wheat and butter pastry — fructans and lactose.")),
        new("bagel", null, new("", "Bagel", "High-FODMAP Ingredient", "Medium",
            "Wheat-based — contains fructans.")),
        new("wrap", null, new("", "Wrap", "High-FODMAP Ingredient", "Medium",
            "Usually wheat-based wrap — contains fructans.")),
        new("sandwich", null, new("", "Sandwich", "High-FODMAP Ingredient", "Medium",
            "Bread-based — wheat fructans plus fillings may add FODMAP load.")),
        new("taco", null, new("", "Taco", "High-FODMAP Ingredient", "Low",
            "Corn taco shell is low FODMAP but fillings may contain onion/beans.")),
        new("quesadilla", null, new("", "Quesadilla", "High-FODMAP Ingredient", "Medium",
            "Wheat tortilla with cheese — fructans and lactose.")),
        new("risotto", null, new("", "Risotto", "High-FODMAP Ingredient", "Medium",
            "Rice dish but typically contains onion and garlic.")),
        new("dumpling", null, new("", "Dumpling", "High-FODMAP Ingredient", "Medium",
            "Wheat wrapper with fillings often containing garlic and onion.")),
        new("gyoza", null, new("", "Gyoza", "High-FODMAP Ingredient", "Medium",
            "Japanese dumplings — wheat wrapper, garlic and cabbage filling.")),
        new("wonton", null, new("", "Wonton", "High-FODMAP Ingredient", "Medium",
            "Wheat wrappers with fillings often containing garlic/onion.")),
        new("samosa", null, new("", "Samosa", "High-FODMAP Ingredient", "Medium",
            "Wheat pastry stuffed with potato and onion.")),
        new("empanada", null, new("", "Empanada", "High-FODMAP Ingredient", "Medium",
            "Wheat pastry with onion-containing filling.")),
        new("biryani", null, new("", "Biryani", "High-FODMAP Ingredient", "Medium",
            "Spiced rice with onion and garlic.")),

        // ── Dried Fruits ──
        new("dried mango", null, new("", "Dried Mango", "Fructose Source", "Medium",
            "Concentrated fructose from dehydration.")),
        new("dried apricot", null, new("", "Dried Apricot", "Polyol Source", "Medium",
            "Concentrated sorbitol from dehydration.")),
        new("dried fig", null, new("", "Dried Fig", "Fructose Source", "Medium",
            "Concentrated fructose from dehydration.")),
        new("date", null, new("", "Dates", "Fructose Source", "Medium",
            "Dates contain moderate excess fructose — higher when dried.")),
        new("trail mix", null, new("", "Trail Mix", "Polyol Source", "Medium",
            "Often contains dried stone fruits and cashews/pistachios — mixed FODMAP triggers.")),
        new("raisin", null, new("", "Raisins", "Fructose Source", "Low",
            "Raisins contain moderate fructose — generally tolerated in small amounts.")),

        // ── Condiments & Sauces ──
        new("soy sauce", null, new("", "Soy Sauce", "High-FODMAP Ingredient", "Low",
            "Small amounts of wheat in fermentation — generally low FODMAP in typical servings.")),
        new("bbq sauce", null, new("", "BBQ Sauce", "Fructose Source", "Medium",
            "Often contains HFCS, onion, and garlic.")),
        new("tomato sauce", null, new("", "Tomato Sauce", "High-FODMAP Ingredient", "Low",
            "Plain tomato sauce is low FODMAP but commercial versions often add onion/garlic.")),
        new("ketchup", null, new("", "Ketchup", "Fructose Source", "Low",
            "Contains moderate sugar/HFCS but typically used in small amounts.")),
        new("mayonnaise", null, new("", "Mayonnaise", "High-FODMAP Ingredient", "Low",
            "Plain mayo is generally low FODMAP — egg, oil, and vinegar base.")),
        new("mustard", null, new("", "Mustard", "High-FODMAP Ingredient", "Low",
            "Plain mustard is generally low FODMAP in typical serving sizes.")),
        new("pesto", null, new("", "Pesto", "High-FODMAP Ingredient", "Medium",
            "Traditional pesto contains garlic. Pine nut base is low FODMAP.")),
        new("salsa", null, new("", "Salsa", "High-FODMAP Ingredient", "Medium",
            "Often contains onion and garlic.")),
        new("hoisin sauce", null, new("", "Hoisin Sauce", "High-FODMAP Ingredient", "Medium",
            "Contains garlic and sometimes wheat.")),
        new("teriyaki sauce", null, new("", "Teriyaki Sauce", "High-FODMAP Ingredient", "Medium",
            "Contains soy sauce (wheat) and often garlic/onion.")),
    ];
}
