namespace GutAI.Infrastructure.Services;

/// <summary>
/// Canonical severity ratings for ingredients assessed by both FodmapService and GutRiskService.
/// Both services MUST reference these values to prevent contradictory assessments.
/// Based on Monash University FODMAP research and peer-reviewed studies.
/// </summary>
internal static class SharedFodmapSeverities
{
    /// <summary>
    /// Maps canonical ingredient names to their agreed FODMAP severity.
    /// Key = lowercase ingredient name, Value = severity ("High", "Moderate", "Low").
    /// Both FodmapData and GutRiskData MUST derive their severity from these values.
    /// GutRiskData maps "Moderate" → "Medium" via ToRiskLevel().
    /// </summary>
    // Exposed as IReadOnlyDictionary — a mutable public static Dictionary would let any
    // caller silently redefine canonical severities process-wide.
    public static readonly IReadOnlyDictionary<string, string> Severities = BuildSeverities();

    private static Dictionary<string, string> BuildSeverities() => new(StringComparer.OrdinalIgnoreCase)
    {
        // Fructans
        ["wheat"] = "High",
        ["barley"] = "High",
        ["rye"] = "High",
        ["onion"] = "High",
        ["garlic"] = "High",
        ["shallot"] = "High",
        ["leek"] = "Moderate",
        ["artichoke"] = "High",
        ["inulin"] = "High",
        ["chicory root"] = "High",
        ["fructooligosaccharide"] = "High",
        ["asparagus"] = "Moderate",
        ["beetroot"] = "Moderate",
        ["brussels sprout"] = "Moderate",
        ["pistachio"] = "High",
        ["cashew"] = "High",
        ["spelt"] = "Moderate",
        ["wheat starch"] = "Moderate",
        ["fennel"] = "Moderate",
        ["oligofructose"] = "High",
        ["banana"] = "Moderate",
        ["sweet corn"] = "Moderate",
        ["celeriac"] = "Moderate",
        ["kimchi"] = "Moderate",
        ["kamut"] = "Moderate",
        ["farro"] = "Moderate",
        ["freekeh"] = "High",

        // GOS
        ["chickpea"] = "High",
        ["lentil"] = "High",
        ["kidney bean"] = "High",
        ["black bean"] = "High",
        ["soybean"] = "High",
        ["split pea"] = "High",
        ["navy bean"] = "High",
        ["pinto bean"] = "High",
        ["lima bean"] = "High",
        ["baked bean"] = "High",
        ["broad bean"] = "High",
        ["fava bean"] = "High",
        ["cannellini"] = "High",
        ["edamame"] = "Moderate",
        ["hummus"] = "Moderate",
        ["lupin"] = "High",
        ["soy milk"] = "Moderate",
        ["soy flour"] = "High",
        ["soy protein"] = "Moderate",
        ["pea protein"] = "Moderate",
        ["aquafaba"] = "High",
        ["mangetout"] = "Moderate",
        ["haricot bean"] = "High",
        ["borlotti"] = "High",
        ["mung bean"] = "Moderate",
        ["adzuki"] = "High",
        ["garbanzo"] = "High",

        // Lactose
        ["milk"] = "High",
        ["milk powder"] = "High",
        ["lactose"] = "High",
        ["yogurt"] = "Moderate",
        ["cream"] = "Moderate",
        ["ice cream"] = "High",
        ["cottage cheese"] = "High",
        ["ricotta"] = "High",
        ["buttermilk"] = "Moderate",
        ["cream cheese"] = "Moderate",
        ["whey powder"] = "Moderate",
        ["whey concentrate"] = "Moderate",
        ["milk solid"] = "High",
        ["condensed milk"] = "High",
        ["mascarpone"] = "High",
        ["paneer"] = "High",
        ["kefir"] = "Low",
        ["quark"] = "Moderate",
        ["halloumi"] = "Moderate",
        ["sour cream"] = "Moderate",
        ["fresh mozzarella"] = "Moderate",

        // Excess Fructose
        ["honey"] = "High",
        ["agave"] = "High",
        ["high fructose corn syrup"] = "High",
        ["apple"] = "High",
        ["pear"] = "High",
        ["mango"] = "High",
        ["watermelon"] = "High",
        ["apple juice"] = "High",
        ["pear juice"] = "High",
        ["fruit juice concentrate"] = "High",
        ["crystalline fructose"] = "High",
        ["date syrup"] = "High",

        // Polyols
        ["sorbitol"] = "High",
        ["mannitol"] = "High",
        ["maltitol"] = "High",
        ["xylitol"] = "High",
        ["mushroom"] = "High",
        ["cauliflower"] = "High",
        ["avocado"] = "Moderate",
        ["sweet potato"] = "Moderate",
        ["erythritol"] = "Low",
        ["isomalt"] = "High",
        ["lactitol"] = "High",
        ["prune"] = "High",
        ["cherry"] = "Moderate",
        ["apricot"] = "Moderate",
        ["peach"] = "Moderate",
        ["plum"] = "Moderate",
        ["nectarine"] = "Moderate",
        ["blackberry"] = "Moderate",
        ["celery"] = "Moderate",

        // ── Completed governance coverage (hardening pass) ──
// Values copied verbatim from FodmapData lists; Resolve() now serves them.
        ["acacia gum"] = "Low",
        ["acai bowl"] = "Moderate",
        ["alfredo"] = "High",
        ["almond milk"] = "Low",
        ["baba ganoush"] = "Moderate",
        ["bangers and mash"] = "Moderate",
        ["bao"] = "Moderate",
        ["barbecue sauce"] = "Moderate",
        ["bean flour"] = "High",
        ["bean paste"] = "High",
        ["besan"] = "High",
        ["bibimbap"] = "Moderate",
        ["black-eyed pea"] = "High",
        ["blackberries"] = "Moderate",
        ["bolognese"] = "High",
        ["boysenberry"] = "High",
        ["brioche"] = "High",
        ["brown rice syrup"] = "Low",
        ["bruschetta"] = "High",
        ["bulgur"] = "High",
        ["burrito bowl"] = "Moderate",
        ["butter"] = "Low",
        ["butter bean"] = "High",
        ["butter chicken"] = "High",
        ["caesar dressing"] = "Moderate",
        ["calzone"] = "High",
        ["cane sugar"] = "Low",
        ["carbonara"] = "High",
        ["casein"] = "Low",
        ["caseinate"] = "Low",
        ["cereal"] = "Moderate",
        ["cereal bar"] = "Moderate",
        ["chai"] = "Moderate",
        ["chana"] = "High",
        ["chana masala"] = "High",
        ["chanterelle"] = "Moderate",
        ["cheese spread"] = "Moderate",
        ["cherries"] = "Moderate",
        ["chicken parma"] = "High",
        ["chickpea flour"] = "High",
        ["chicory coffee"] = "High",
        ["chicory fibre"] = "High",
        ["chili con carne"] = "High",
        ["chole"] = "High",
        ["chutney"] = "Moderate",
        ["clam chowder"] = "High",
        ["clotted cream"] = "Moderate",
        ["coconut milk"] = "Low",
        ["coconut nectar"] = "Moderate",
        ["coconut water"] = "Moderate",
        ["corn dog"] = "Moderate",
        ["corn on the cob"] = "Moderate",
        ["couscous"] = "High",
        ["cracker"] = "Moderate",
        ["cream of mushroom"] = "High",
        ["crouton"] = "High",
        ["crumpet"] = "Moderate",
        ["currant"] = "Moderate",
        ["custard"] = "High",
        ["dal"] = "High",
        ["dal makhani"] = "High",
        ["dal tadka"] = "High",
        ["dandelion"] = "Moderate",
        ["danish pastry"] = "High",
        ["dessert wine"] = "Moderate",
        ["dhal"] = "High",
        ["dim sum"] = "Moderate",
        ["dolma"] = "Moderate",
        ["doner"] = "Moderate",
        ["dosa"] = "Moderate",
        ["dried apple"] = "High",
        ["dried cherry"] = "High",
        ["dried cranberry"] = "Moderate",
        ["dried date"] = "High",
        ["dried peach"] = "High",
        ["dried pear"] = "High",
        ["dried pineapple"] = "Moderate",
        ["dulce de leche"] = "High",
        ["dumpling"] = "Moderate",
        ["durum"] = "High",
        ["einkorn"] = "High",
        ["enchilada"] = "High",
        ["enoki"] = "Moderate",
        ["evaporated milk"] = "High",
        ["faba bean protein"] = "High",
        ["falafel"] = "High",
        ["fat free milk"] = "High",
        ["fattoush"] = "Moderate",
        ["fiber supplement"] = "High",
        ["fig"] = "Moderate",
        ["fish finger"] = "Moderate",
        ["fish sauce"] = "Low",
        ["focaccia"] = "High",
        ["french onion"] = "High",
        ["french toast"] = "High",
        ["fried chicken"] = "Moderate",
        ["fried rice"] = "Moderate",
        ["fructose-glucose syrup"] = "High",
        ["fruit leather"] = "High",
        ["fruit nectar"] = "Moderate",
        ["fruit sugar"] = "High",
        ["garlic powder"] = "High",
        ["garlic salt"] = "High",
        ["ghee"] = "Low",
        ["glucose-fructose syrup"] = "High",
        ["goat cheese"] = "Moderate",
        ["golden syrup"] = "Moderate",
        ["gram flour"] = "High",
        ["granola"] = "Moderate",
        ["grape juice"] = "Moderate",
        ["gravy"] = "Moderate",
        ["grilled cheese"] = "High",
        ["guacamole"] = "Moderate",
        ["guava"] = "Moderate",
        ["gyro"] = "Moderate",
        ["half and half"] = "Moderate",
        ["haricot"] = "High",
        ["hemp milk"] = "Low",
        ["hoisin"] = "Moderate",
        ["hot dog"] = "Moderate",
        ["hydrogenated starch"] = "High",
        ["idli"] = "Moderate",
        ["imo syrup"] = "Moderate",
        ["infant formula"] = "Moderate",
        ["invert sugar"] = "Moderate",
        ["isomalto-oligosaccharide"] = "Moderate",
        ["jackfruit"] = "Moderate",
        ["katsu"] = "Moderate",
        ["kebab"] = "Moderate",
        ["korma"] = "High",
        ["laksa"] = "Moderate",
        ["lasagne"] = "High",
        ["lentil flour"] = "High",
        ["longan"] = "Moderate",
        ["low fat milk"] = "High",
        ["lychee"] = "Moderate",
        ["mac and cheese"] = "High",
        ["marmalade"] = "Moderate",
        ["mayonnaise"] = "Low",
        ["milk chocolate"] = "Moderate",
        ["milk protein concentrate"] = "Moderate",
        ["minestrone"] = "High",
        ["miso"] = "Low",
        ["modified wheat starch"] = "Moderate",
        ["moussaka"] = "High",
        ["muesli"] = "Moderate",
        ["nachos"] = "Moderate",
        ["oat milk"] = "Low",
        ["okonomiyaki"] = "High",
        ["onion powder"] = "High",
        ["onion ring"] = "High",
        ["onion salt"] = "High",
        ["oyster mushroom"] = "High",
        ["oyster sauce"] = "Moderate",
        ["palak paneer"] = "High",
        ["panko"] = "High",
        ["pasta sauce"] = "Moderate",
        ["pasty"] = "High",
        ["persimmon"] = "High",
        ["pesto"] = "Moderate",
        ["pho"] = "Moderate",
        ["pizza sauce"] = "Moderate",
        ["poke bowl"] = "Low",
        ["pomegranate"] = "Moderate",
        ["porcini"] = "High",
        ["porridge"] = "Low",
        ["port"] = "Moderate",
        ["portobello"] = "High",
        ["prebiotic"] = "High",
        ["pretzel"] = "High",
        ["processed cheese"] = "Moderate",
        ["protein bar"] = "Moderate",
        ["psyllium"] = "Low",
        ["pumpernickel"] = "High",
        ["quesadilla"] = "Moderate",
        ["quiche"] = "High",
        ["radicchio"] = "Moderate",
        ["rajma"] = "High",
        ["ranch dressing"] = "Moderate",
        ["ravioli"] = "High",
        ["reduced fat milk"] = "High",
        ["refried bean"] = "High",
        ["relish"] = "Moderate",
        ["resistant starch"] = "Low",
        ["rice malt syrup"] = "Low",
        ["rice milk"] = "Low",
        ["risotto"] = "Moderate",
        ["rogan josh"] = "High",
        ["rum"] = "Low",
        ["salsa"] = "Moderate",
        ["sambar"] = "High",
        ["sauerkraut"] = "Moderate",
        ["sausage roll"] = "High",
        ["savoy cabbage"] = "Moderate",
        ["scallion"] = "High",
        ["schnitzel"] = "Moderate",
        ["scone"] = "Moderate",
        ["scotch egg"] = "Moderate",
        ["seasoning mix"] = "Moderate",
        ["seitan"] = "High",
        ["semolina"] = "High",
        ["shakshuka"] = "High",
        ["shawarma"] = "Moderate",
        ["shiitake"] = "High",
        ["smoothie bowl"] = "Moderate",
        ["snow pea"] = "Moderate",
        ["souvlaki"] = "Moderate",
        ["soy sauce"] = "Low",
        ["spanakopita"] = "High",
        ["spring onion"] = "High",
        ["spring roll"] = "Moderate",
        ["stir fry"] = "Moderate",
        ["stock cube"] = "Moderate",
        ["stuffing"] = "High",
        ["sugar free"] = "High",
        ["sugar snap"] = "Moderate",
        ["sugar-free"] = "High",
        ["sugar-free candy"] = "High",
        ["sugar-free chocolate"] = "High",
        ["sugar-free gum"] = "High",
        ["sugar-free mint"] = "High",
        ["sultana"] = "Moderate",
        ["sun-dried tomato"] = "Moderate",
        ["sushi"] = "Low",
        ["sweet chilli sauce"] = "Moderate",
        ["tabbouleh"] = "High",
        ["tamarillo"] = "High",
        ["tandoori"] = "Moderate",
        ["tapioca"] = "Low",
        ["tempeh"] = "Low",
        ["tempura"] = "Moderate",
        ["teriyaki"] = "Moderate",
        ["teriyaki chicken"] = "Moderate",
        ["tikka masala"] = "High",
        ["tom yum"] = "Moderate",
        ["tomato paste"] = "Moderate",
        ["tortellini"] = "High",
        ["tortilla"] = "Moderate",
        ["trail mix"] = "Moderate",
        ["treacle"] = "Moderate",
        ["triticale"] = "High",
        ["truffle"] = "High",
        ["tzatziki"] = "Moderate",
        ["vindaloo"] = "High",
        ["vital wheat gluten"] = "High",
        ["wafer"] = "Moderate",
        ["wheat bran"] = "High",
        ["wheat dextrin"] = "Moderate",
        ["wheat flour"] = "High",
        ["wheat germ"] = "High",
        ["wheat gluten"] = "High",
        ["whey permeate"] = "High",
        ["whey protein isolate"] = "Low",
        ["whipping cream"] = "Moderate",
        ["white chocolate"] = "Moderate",
        ["whole milk"] = "High",
        ["whole wheat"] = "High",
        ["wonton"] = "Moderate",
        ["worcestershire"] = "Moderate",
        ["yoghurt"] = "Moderate",
        ["butternut squash"] = "Moderate",
        ["polydextrose"] = "Moderate",
        ["glycerol"] = "Low",
        ["polyglycitol"] = "Moderate",
    };

    /// <summary>
    /// Converts a FODMAP severity ("High"/"Moderate"/"Low") to a GutRisk risk level
    /// ("High"/"Medium"/"Low"). The only mapping difference is Moderate → Medium.
    /// </summary>
    public static string ToRiskLevel(string fodmapSeverity)
        => fodmapSeverity == "Moderate" ? "Medium" : fodmapSeverity;

    /// <summary>
    /// Gets the risk level for GutRiskData from the shared severities map.
    /// Returns null if the ingredient is not in the shared map.
    /// </summary>
    public static string? GetRiskLevel(string ingredient)
        => Severities.TryGetValue(ingredient, out var sev) ? ToRiskLevel(sev) : null;

    /// <summary>
    /// Derivation API for dataset entries: canonical value when governed, otherwise the
    /// entry's curated fallback. Makes drift impossible for keyed entries instead of
    /// merely detectable.
    /// </summary>
    public static string Resolve(string key, string fallback)
        => Severities.TryGetValue(key, out var v) ? v : fallback;
}
